/* expert.js */
const EXPERT_STORAGE_KEY="bamco-vehicle-expert-weights";
const DEFAULT_EXPERT_WEIGHTS=Object.fromEntries(Array.from({length:15},(_,index)=>[String(index+1),"1/15"]));
let expertState={info:{completionDate:new Date().toISOString().slice(0,10)},weights:{...DEFAULT_EXPERT_WEIGHTS},confirmed:false,confirmedSnapshot:null};
try{const saved=JSON.parse(localStorage.getItem(EXPERT_STORAGE_KEY));if(saved)expertState={...expertState,...saved,info:{...expertState.info,...(saved.info||{})},weights:{...(saved.weights||{})}}}catch(_){}
window.ASSESSMENT_CRITERIA?.forEach(main=>{const current=String(expertState.weights[main.id]??"").trim();expertState.weights[main.id]=current===""?DEFAULT_EXPERT_WEIGHTS[String(main.id)]:sanitizeWeight(current)});
const legacyEqualWeights=window.ASSESSMENT_CRITERIA?.every((main,index)=>String(expertState.weights[main.id])===(index===14?"0.062":"0.067"));
if(legacyEqualWeights)expertState.weights={...DEFAULT_EXPERT_WEIGHTS};

const expertText={
  fa:{title:"فرم وزن‌دهی شاخص‌های ارزیابی",subtitle:"وزن هر شاخص اصلی را به‌صورت عددی وارد کنید. مجموع وزن‌ها باید دقیقاً برابر ۱ باشد.",infoTitle:"اطلاعات خبره",name:"نام و نام خانوادگی",specialty:"تخصص",position:"سمت",organization:"سازمان",experience:"سابقه کاری",phone:"شماره تماس",email:"ایمیل",date:"تاریخ تکمیل فرم",weightsTitle:"وزن شاخص‌های اصلی",weight:"وزن واردشده",total:"مجموع وزن ثبت‌شده",remaining:"مقدار باقی‌مانده تا رسیدن به یک",valid:"مجموع وزن‌ها دقیقاً برابر ۱ است.",low:"مجموع وزن‌ها کمتر از ۱ است.",high:"مجموع وزن‌ها بیشتر از ۱ است.",confirm:"تأیید نهایی",confirmed:"وزن‌ها تأیید و ذخیره شدند.",excel:"خروجی اکسل",reset:"بازنشانی وزن‌ها",resetConfirm:"اطلاعات خبره پاک و وزن‌ها به حالت پیش‌فرض بازگردانده شوند؟",excelError:"ماژول خروجی اکسل بارگذاری نشده است."},
  en:{title:"Assessment Criteria Weighting Form",subtitle:"Enter a numeric weight for each main criterion. The sum of all weights must equal exactly 1.",infoTitle:"Expert Information",name:"Full Name",specialty:"Area of Expertise",position:"Position / Job Title",organization:"Organization",experience:"Work Experience",phone:"Phone Number",email:"Email Address",date:"Form Completion Date",weightsTitle:"Main-Criterion Weights",weight:"Weight",total:"Total Weight",remaining:"Remaining to 1",valid:"The total weight equals exactly 1.",low:"The total weight is less than 1.",high:"The total weight is greater than 1.",incomplete:"Complete all required expert information and provide at least a phone number or an email address.",confirm:"Final Confirmation",confirmed:"The weights have been confirmed and saved.",excel:"Download Excel Output",reset:"Clear Form",resetConfirm:"Clear the expert information and all entered weights?",excelError:"The Excel export module did not load."}
};
expertText.fa.completionDate=expertText.fa.date;
expertText.en.completionDate=expertText.en.date;
function et(key){return expertText[locale][key]||key}
function latinDigits(value){return String(value??"").replace(/[۰-۹]/g,d=>"0123456789"["۰۱۲۳۴۵۶۷۸۹".indexOf(d)]).replace(/[٠-٩]/g,d=>"0123456789"["٠١٢٣٤٥٦٧٨٩".indexOf(d)]).replace("٫",".")}
function persianDigits(value){return String(value??"").replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[d])}
function sanitizeWeight(value){const normalized=latinDigits(value).replace(/[^\d./]/g,"");if(normalized.includes("/")){const [numerator,denominator]=normalized.split("/");return `${(numerator||"").slice(0,3)}/${(denominator||"").slice(0,3)}`}const parts=normalized.split(".");return parts.length>1?`${parts.shift()||"0"}.${parts.join("").slice(0,3)}`:parts[0]}
function shownWeight(value){return locale==="fa"?persianDigits(value):String(value??"")}
function numericWeight(value){const normalized=latinDigits(value);if(normalized.includes("/")){const [numerator,denominator]=normalized.split("/").map(Number);return denominator?numerator/denominator:0}return Number(normalized)||0}
function expertTotal(){return Object.values(expertState.weights).reduce((sum,value)=>sum+numericWeight(value),0)}
function expertWeightsComplete(){return window.ASSESSMENT_CRITERIA.every(main=>String(expertState.weights[main.id]??"").trim()!=="")}
function persistExpert(){localStorage.setItem(EXPERT_STORAGE_KEY,JSON.stringify(expertState))}
window.getExpertBackup=function(){return JSON.parse(JSON.stringify(expertState))};
window.restoreExpertBackup=function(data){
  if(!data||typeof data!=="object")return;
  const restoredInfo={completionDate:new Date().toISOString().slice(0,10),...(data.info||{})};
  const restoredWeights={...DEFAULT_EXPERT_WEIGHTS,...(data.weights||{})};
  window.ASSESSMENT_CRITERIA?.forEach(main=>{const value=String(restoredWeights[main.id]??"").trim();restoredWeights[main.id]=value===""?DEFAULT_EXPERT_WEIGHTS[String(main.id)]:sanitizeWeight(value)});
  expertState={info:restoredInfo,weights:restoredWeights,confirmed:!!data.confirmed};
  persistExpert();
  if(typeof currentRole!=="undefined"&&currentRole==="expert"&&window.renderExpertPanel)window.renderExpertPanel();
};
function expertField(key,type="text"){
  const isDate=key==="completionDate";
  const value=isDate&&typeof formatAssessmentDate==="function"?formatAssessmentDate(expertState.info[key]):expertState.info[key]||"";
  const localized=key==="experience"||key==="phone";
  const shown=localized&&locale==="fa"?faNum(value):value;
  return `<label><span>${et(key)}</span><input data-expert-info="${key}" type="${isDate?"text":type}" value="${esc(shown)}" ${type==="email"?'dir="ltr"':""} ${localized?'data-localized-number="true" inputmode="numeric"':""} ${isDate?'class="jalaliDateInput expertJalaliDate" inputmode="none" readonly':""}></label>`
}
function renderExpertStatus(){const total=expertTotal(),validTotal=Math.abs(total-1)<1e-9,complete=expertWeightsComplete();const status=document.querySelector("#expertWeightStatus");if(!status)return;const kind=validTotal?"valid":total<1?"low":"high";const remaining=1-total;const totalValue=document.querySelector("#expertTotalValue"),remainingValue=document.querySelector("#expertRemainingValue");if(totalValue)totalValue.textContent=shownWeight(total.toFixed(3));if(remainingValue)remainingValue.textContent=shownWeight((Math.abs(remaining)<1e-9?0:remaining).toFixed(3));status.className=`expertWeightStatus ${kind}`;status.textContent=et(kind);const confirmButton=document.querySelector("#expertConfirmButton"),excelButton=document.querySelector("#expertExcelButton");if(confirmButton)confirmButton.disabled=!(validTotal&&complete);if(excelButton)excelButton.disabled=!(validTotal&&complete);}
function renderExpertPanel(){const panel=document.querySelector("#expertPanel");if(!panel)return;panel.innerHTML=`
  <section class="card expertInfoCard"><div class="sectionTitle"><div><h2>${et("infoTitle")}</h2></div></div><div class="expertInfoGrid">${expertField("name")}${expertField("specialty")}${expertField("position")}${expertField("organization")}${expertField("experience")}${expertField("phone","tel")}${expertField("email","email")}${expertField("completionDate","date")}</div></section>
  <section class="expertStatusCard"><div class="expertLiveSummary"><span>${et("total")} <strong id="expertTotalValue">${shownWeight("1.000")}</strong></span><span>${et("remaining")} <strong id="expertRemainingValue">${shownWeight("0.000")}</strong></span><div id="expertWeightStatus" class="expertWeightStatus valid"></div></div></section>
  <section class="expertWeightsSection"><div class="expertSectionHead"><div><h2>${et("weightsTitle")}</h2><p>${locale==="fa"?"وزن پیش‌فرض همه شاخص‌ها ۱/۱۵ است؛ مقدارها قابل تغییر هستند و اعداد اعشاری تا سه رقم پذیرفته می‌شوند.":"Each criterion defaults to 1/15. Values remain editable, and decimals may contain up to three places."}</p></div></div><div class="expertWeightGrid">${window.ASSESSMENT_CRITERIA.map((main,index)=>`<article class="expertWeightCard">${criterionIcon(index)}<div><h3>${title(main.titleFa,"main",main.id)}</h3></div><label><span>${et("weight")}</span><input data-expert-weight="${main.id}" type="text" inputmode="decimal" value="${esc(shownWeight(expertState.weights[main.id]??""))}" placeholder="${shownWeight("1/15")}"></label></article>`).join("")}</div></section>`;
  panel.querySelectorAll("[data-expert-info]").forEach(input=>{if(input.dataset.expertInfo==="completionDate"){const open=()=>openJalaliCalendarFor(input,expertState.info.completionDate,date=>{expertState.info.completionDate=date;expertState.confirmed=false;persistExpert();renderExpertStatus()});input.addEventListener("click",open);input.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open()}})}else input.addEventListener("input",event=>{if(event.target.dataset.localizedNumber&&locale==="fa")event.target.value=faNum(event.target.value);expertState.info[event.target.dataset.expertInfo]=event.target.value;expertState.confirmed=false;persistExpert();renderExpertStatus()})});
  panel.querySelectorAll("[data-expert-weight]").forEach(input=>input.addEventListener("input",event=>{const value=sanitizeWeight(event.target.value);expertState.weights[event.target.dataset.expertWeight]=value;event.target.value=shownWeight(value);expertState.confirmed=false;persistExpert();renderExpertStatus()}));
  const confirmButton=document.querySelector("#expertConfirmButton"),excelButton=document.querySelector("#expertExcelButton"),resetButton=document.querySelector("#expertResetButton");confirmButton.textContent=et("confirm");excelButton.textContent=et("excel");resetButton.textContent=et("reset");confirmButton.onclick=()=>{expertState.confirmed=true;expertState.confirmedSnapshot={weights:{...expertState.weights},info:{...expertState.info},confirmedAt:new Date().toISOString()};persistExpert();if(window.applyConfirmedExpertWeights)window.applyConfirmedExpertWeights(window.getExpertBackup());if(window.BAMCO_COMPLETE_EDIT_AUTHORIZATION)window.BAMCO_COMPLETE_EDIT_AUTHORIZATION("expert");renderExpertStatus();alert(et("confirmed"))};excelButton.onclick=exportExpertExcel;resetButton.onclick=()=>{if(!confirm(et("resetConfirm")))return;expertState={info:{completionDate:new Date().toISOString().slice(0,10)},weights:{...DEFAULT_EXPERT_WEIGHTS},confirmed:false,confirmedSnapshot:null};persistExpert();if(window.onExpertWeightsCleared)window.onExpertWeightsCleared();renderExpertPanel()};
  renderExpertStatus();
}
window.renderExpertPanel=renderExpertPanel;

async function exportExpertExcel(){
  if(!window.ExcelJS){alert(et("excelError"));return}
  if(!(Math.abs(expertTotal()-1)<1e-9&&expertWeightsComplete()))return;
  const expertCommentInput=document.querySelector('[data-final-comment="expert"]');
  if(expertCommentInput){state.finalComments=state.finalComments||{};state.finalComments.expert=expertCommentInput.value||"";if(typeof persist==="function")persist()}
  const fa=locale==="fa",wb=new ExcelJS.Workbook();wb.creator="BAM Automotive Company";wb.created=new Date();
  const ws=wb.addWorksheet(fa?"وزن شاخص‌ها":"Criterion Weights");ws.views=[{rightToLeft:fa,showGridLines:false}];ws.properties.defaultRowHeight=23;
  ws.mergeCells("A1:C1");ws.getCell("A1").value=fa?"فرم وزن‌دهی شاخص‌های ارزیابی خودرو":"Vehicle Assessment Criteria Weighting Form";ws.getCell("A1").font={bold:true,size:17,color:{argb:"FF163B69"}};ws.getCell("A1").alignment={horizontal:"center"};ws.getRow(1).height=32;
  const infoRows=[[et("name"),expertState.info.name],[et("specialty"),expertState.info.specialty],[et("position"),expertState.info.position],[et("organization"),expertState.info.organization],[et("experience"),window.getExpertExperienceDisplay?window.getExpertExperienceDisplay(locale):expertState.info.experience],[et("phone"),expertState.info.phone||""],[et("email"),expertState.info.email||""],[et("date"),typeof formatAssessmentDate==="function"?formatAssessmentDate(expertState.info.completionDate,true):expertState.info.completionDate]];
  infoRows.forEach((row,index)=>{ws.getCell(index+3,1).value=row[0];ws.getCell(index+3,2).value=row[1];ws.getCell(index+3,1).font={bold:true,color:{argb:"FF244B70"}};ws.getCell(index+3,1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFEAF3F8"}}});
  ws.getCell(12,1).value=fa?"نظر نهایی خبره":"Expert Final Comment";ws.getCell(12,1).font={bold:true,color:{argb:"FF244B70"}};ws.getCell(12,1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFEAF3F8"}};
  ws.mergeCells("A13:C15");ws.getCell("A13").value=state.finalComments?.expert||"";ws.getCell("A13").alignment={horizontal:fa?"right":"left",vertical:"top",wrapText:true};ws.getCell("A13").border={top:{style:"thin",color:{argb:"FFD8E3EA"}},bottom:{style:"thin",color:{argb:"FFD8E3EA"}},left:{style:"thin",color:{argb:"FFD8E3EA"}},right:{style:"thin",color:{argb:"FFD8E3EA"}}};[13,14,15].forEach(r=>ws.getRow(r).height=24);
  const headerRow=17;ws.getRow(headerRow).values=[fa?"ردیف":"No.",fa?"نام شاخص اصلی":"Main Criterion",et("weight")];ws.getRow(headerRow).eachCell(cell=>{cell.font={bold:true,color:{argb:"FFFFFFFF"}};cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF0B5B98"}};cell.alignment={horizontal:"center",vertical:"middle"}});
  window.ASSESSMENT_CRITERIA.forEach((main,index)=>{const row=ws.getRow(headerRow+1+index);row.values=[index+1,title(main.titleFa,"main",main.id),numericWeight(expertState.weights[main.id])];row.getCell(3).numFmt="0.000000";if(index%2===1)row.eachCell(cell=>cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFF3F8FB"}})});
  const totalRow=headerRow+1+window.ASSESSMENT_CRITERIA.length;ws.getCell(totalRow,2).value=et("total");ws.getCell(totalRow,2).font={bold:true};ws.getCell(totalRow,3).value={formula:`SUM(C${headerRow+1}:C${totalRow-1})`,result:1};ws.getCell(totalRow,3).numFmt="0.000";ws.getRow(totalRow).eachCell(cell=>{cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFDDF4E9"}};cell.font={bold:true,color:{argb:"FF08734B"}}});
  ws.columns=[{width:10},{width:58},{width:18}];ws.getColumn(2).alignment={wrapText:true,vertical:"middle"};ws.autoFilter={from:{row:headerRow,column:1},to:{row:totalRow-1,column:3}};ws.views=[{state:"frozen",ySplit:headerRow,rightToLeft:fa,showGridLines:false}];
  const buffer=await wb.xlsx.writeBuffer(),blob=new Blob([buffer],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`criterion_weights_${window.englishFileToken?window.englishFileToken(expertState.info.name,"expert"):"expert"}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}
