/* app.js */
let activeMain="1";
let state={metadata:{date:isoLocal(new Date())},scores:{},notes:{},weights:{},attachments:{},vehiclePhotos:{},finalComments:{evaluator:"",expert:"",manager:""}};
let currentRole="evaluator";
let locale="fa";
const $=selector=>document.querySelector(selector);
const faNum=value=>String(value).replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[d]);
const enNum=value=>String(value).replace(/[۰-۹]/g,d=>"0123456789"["۰۱۲۳۴۵۶۷۸۹".indexOf(d)]);
const T={
fa:{brand:"خودروسازان بم",brandSub:"سامانه ارزیابی توصیفی خودروهای سواری",heroEyebrow:"فرم ارزیابی جامع",heroTitle:"ارزیابی توصیفی خودروهای سواری",heroText:"ثبت منسجم مشاهدات، امتیازدهی شاخص‌ها و ارائهٔ جمع‌بندی مدیریتی",finalScore:"امتیاز نهایی",outOfFive:"از ۱۰",assessmentInfo:"اطلاعات ارزیابی",evaluator:"نام ارزیاب",date:"تاریخ ارزیابی",brandLabel:"برند خودرو",model:"مدل خودرو",vin:"شماره شاسی خودرو",odometer:"کارکرد (کیلومتر)",completion:"تکمیل ارزیابی",verdict:"نتیجه ارزیابی",save:"ذخیره پرونده",exportExcel:"خروجی اکسل",load:"باز کردن پرونده",print:"چاپ گزارش",newAssessment:"شروع ارزیابی جدید",ready:"آماده",saved:"ذخیره شد",score:"امتیاز",notes:"یادداشت ارزیاب",criteria:"شاخص‌های ارزیابی",selected:"شاخص منتخب",guidance:"راهنمای ارزیابی",scoreSummary:"خلاصه امتیازها",summaryText:"نمای مدیریتی عملکرد و سهم وزنی هر شاخص",average:"میانگین",weight:"وزن",weightedScore:"نمره وزن‌دار",outOf:"از ۱۰",newConfirm:"آیا از شروع ارزیابی جدید مطمئن هستید؟ همهٔ اطلاعات ارزیابی، نظر ارزیاب، اطلاعات و وزن‌های خبره و سوابق پرونده پاک می‌شوند و صفحه از نو بارگذاری خواهد شد. این عمل قابل بازگردانی نیست.",loadError:"فایل ارزیابی قابل‌خواندن نیست.",placeholder:"مشاهده، مغایرت یا نکتهٔ قابل‌پیگیری را ثبت کنید.",addNote:"افزودن یادداشت یا تصویر",closeNote:"بستن",attachments:"بارگذاری عکس",recordVoice:"ضبط صدا",stopRecording:"پایان ضبط",remove:"حذف",attachmentLimit:"برای حفظ عملکرد نسخهٔ آفلاین، حجم هر عکس باید حداکثر ۸ مگابایت باشد.",managerView:"نمایش مدیریتی"},
en:{brand:"Bam Automakers Company",brandSub:"Passenger Vehicle Assessment System",heroEyebrow:"Comprehensive Assessment Form",heroTitle:"Passenger Vehicle Assessment",heroText:"A structured workflow for observation, scoring and executive decision support.",finalScore:"Final Score",outOfFive:"out of 10",assessmentInfo:"Assessment Information",evaluator:"Evaluator Name",date:"Assessment Date",brandLabel:"Vehicle Brand",model:"Vehicle Model",vin:"VIN",odometer:"Odometer (km)",completion:"Assessment Completion",verdict:"Assessment Result",save:"Save Assessment",exportExcel:"Export Excel",load:"Open Assessment",print:"Print Report",newAssessment:"Start New Assessment",ready:"Ready",saved:"Saved",score:"Score",notes:"Evaluator Notes",criteria:"Assessment Criteria",selected:"Selected Criterion",guidance:"Assessment Guidance",scoreSummary:"Score Summary",summaryText:"Executive view of performance and weighted contribution",average:"Average",weight:"Weight",weightedScore:"Weighted score",outOf:"out of 10",newConfirm:"Start a new assessment? This will permanently clear the full assessment, evaluator comment, all expert information and weights, and the case history. The page will then reload.",loadError:"The assessment file could not be read.",placeholder:"Record observations, deviations or follow-up items."}
};
Object.assign(T.fa,{scoreGuideTitle:"راهنمای امتیازدهی ۱ تا ۱۰",performanceChart:"مقایسهٔ عملکرد وزن‌دار شاخص‌ها",performanceHint:"اثر نسبی هر شاخص پس از اعمال وزن فعال؛ وزن صفر یعنی اثر صفر",scoreScale:"مقیاس امتیاز: ۰ تا ۱۰"});
Object.assign(T.en,{brandSub:"Passenger Vehicle Descriptive Assessment System",heroTitle:"Passenger Vehicle Descriptive Assessment",heroText:"Structured recording of observations, criterion scoring, and management-level conclusions.",assessmentInfo:"Assessment Details",brandLabel:"Vehicle Make",vin:"Vehicle Identification Number (VIN)",odometer:"Odometer Reading (km)",save:"Save Assessment File",exportExcel:"Export to Excel",load:"Open Assessment File",guidance:"Assessment Instructions",scoreGuideTitle:"Scoring Guide (1–10)",performanceChart:"Weighted Criterion Performance",performanceHint:"Relative criterion impact after applying the active weights; zero weight means zero impact",scoreScale:"Score range: 0–10",addNote:"Add note or photo",attachments:"Upload photo",remove:"Remove",attachmentLimit:"For reliable offline operation, each image must be 8 MB or smaller."});
Object.assign(T.fa,{vehiclePhotosTitle:"تصاویر چهار نمای خودرو",vehiclePhotosHint:"تصاویر نمای جلو، عقب، چپ و راست خودروی مورد ارزیابی را ثبت کنید.",managerPhotosHint:"تصاویر ثبت‌شده توسط ارزیاب",addVehiclePhoto:"افزودن عکس",changeVehiclePhoto:"تعویض عکس",noVehiclePhoto:"عکسی ثبت نشده",frontView:"نمای جلو",rearView:"نمای عقب",leftView:"نمای چپ",rightView:"نمای راست"});
Object.assign(T.en,{vehiclePhotosTitle:"Four Vehicle Views",vehiclePhotosHint:"Add front, rear, left, and right views of the vehicle being assessed.",managerPhotosHint:"Photos recorded by the evaluator",addVehiclePhoto:"Add photo",changeVehiclePhoto:"Change photo",noVehiclePhoto:"No photo recorded",frontView:"Front view",rearView:"Rear view",leftView:"Left view",rightView:"Right view"});
Object.assign(T.fa,{entryAria:"ورود به سامانه",logoAlt:"لوگوی خودروسازان بم",entrySystem:"سامانه ارزیابی خودرو",entryKicker:"سامانه یکپارچه ارزیابی کیفیت",entryWelcome:"به سامانه ارزیابی خودرو خوش آمدید",entryPrompt:"برای ورود، نوع دسترسی خود را انتخاب کنید.",enterEvaluator:"ورود ارزیاب",evaluatorRoleDesc:"ثبت اطلاعات، چک‌لیست، امتیازها و تصاویر مستند",enterExpert:"ورود خبره",expertRoleDesc:"ثبت اطلاعات تخصصی و تعیین وزن شاخص‌های اصلی",enterManager:"ورود مدیریت",managerRoleDesc:"مشاهده داشبورد، نتایج و گزارش مدیریتی",entryOffline:"نسخهٔ آفلاین · اطلاعات فقط روی همین دستگاه نگهداری می‌شود",vehicleName:"نام خودرو",expertName:"نام خبره",outOf100:"از ۱۰۰",qualityDistribution:"توزیع درجه کیفی",qualityDistributionHint:"فراوانی امتیازهای ۱ تا ۱۰ در شاخص‌های دارای وزن فعال",qualityDistributionAria:"نمودار توزیع امتیازهای کیفی",radarTitle:"نمودار عنکبوتی وزن‌دار شاخص‌ها",radarHint:"اثر نسبی هر شاخص پس از اعمال وزن فعال",integratedSummary:"خلاصه یکپارچه شاخص‌ها",integratedSummaryHint:"میانگین هر شاخص از ۱۰، وزن، سهم آن در امتیاز کل و نرخ تکمیل نمایش داده می‌شود.",finalOutOf100:"امتیاز نهایی از ۱۰۰"});
Object.assign(T.en,{entryAria:"System sign-in",logoAlt:"Bam Automakers Company logo",entrySystem:"Vehicle Assessment System",entryKicker:"Integrated Quality Assessment System",entryWelcome:"Welcome to the Vehicle Assessment System",entryPrompt:"Select your access role to continue.",enterEvaluator:"Evaluator Login",evaluatorRoleDesc:"Record vehicle details, checklist scores, notes, and supporting images",enterExpert:"Expert Login",expertRoleDesc:"Enter expert details and assign weights to the main criteria",enterManager:"Management Login",managerRoleDesc:"Review the dashboard, assessment results, and management report",entryOffline:"Offline version · Data is stored only on this device",vehicleName:"Vehicle",expertName:"Expert Name",outOf100:"out of 100",qualityDistribution:"Weighted Quality Rating Distribution",qualityDistributionHint:"Weighted share of scores from 1 to 10 based on the active criterion weights",qualityDistributionAria:"Quality score distribution chart",radarTitle:"Weighted Criteria Radar",radarHint:"Relative criterion impact after applying the active weights",integratedSummary:"Integrated Criteria Summary",integratedSummaryHint:"Shows each criterion average out of 10, weight, contribution to the total score, and completion rate.",finalOutOf100:"Final Score out of 100"});
Object.assign(T.fa,{evaluatorExperience:"سابقه کاری ارزیاب",evaluatorPhone:"شماره تماس ارزیاب",evaluatorEmail:"ایمیل ارزیاب"});
Object.assign(T.en,{brand:"BAM Automotive Company",evaluatorExperience:"Evaluator Work Experience",evaluatorPhone:"Evaluator Phone Number",evaluatorEmail:"Evaluator Email Address"});
Object.assign(T.fa,{footerCompany:"خودروسازان بم",footerSystem:"سامانه آفلاین ارزیابی خودرو",footerDesignedBy:"طراحی شده توسط",footerShahab:"شهاب تنهائیان",footerAnd:"و",footerNazanin:"نازنین قائمی‌زاده"});
Object.assign(T.en,{footerCompany:"BAM Automotive Company",footerSystem:"Offline Vehicle Assessment System",footerDesignedBy:"Designed by",footerShahab:"Shahab Tanhaiyan",footerAnd:"and",footerNazanin:"Nazanin Ghaemizadeh"});
function tr(key){return T[locale][key]||key}
function localNumber(value){return locale==="fa"?faNum(value):enNum(value)}
function clean(text){return String(text||"")
  .replace(/[كيى]/g,char=>({"ك":"ک","ي":"ی","ى":"ی"}[char]))
  .replace(/\u200c{2,}/g,"‌")
  .replace(/ستون\s*([A-Z])/g,"ستون $1")
  .replace(/متوسط\s*(?=[۰-۹\d])/g,"متوسط ")
  .replace(/پایین\s*(?=[۰-۹\d])/g,"پایین ")
  .replace(/نسبتا(?!ً)/g,"نسبتاً")
  .replace(/می\s+شود/g,"می‌شود")
  .replace(/به\s+صورت/g,"به‌صورت")
  .replace(/قابل\s+دسترسی/g,"قابل‌دسترسی")
  .replace(/قابل\s+تشخیص/g,"قابل‌تشخیص")
  .replace(/قابل\s+درک/g,"قابل‌درک")
  .replace(/\s{2,}/g," ")
  .replace(/\s+([،؛:،.])/g,"$1")
  .replace(/\s*–\s*/g," — ")
  .trim()}
function itemKey(main,sub,item){return `${main.id}/${sub.id}/${item.id}`}
function fmt(n){return Number.isFinite(n)?localNumber(n.toFixed(2)):"—"}
const SCORE_LEVELS=[
  {n:10,fa:"ممتاز",en:"Excellent",desc:"فراتر از انتظار؛ بدون نقص قابل مشاهده یا اندازه‌گیری"},{n:9,fa:"بسیار عالی",en:"Very good",desc:"نقص ناچیز، بدون اثر محسوس بر عملکرد یا مشتری"},{n:8,fa:"رقابتی",en:"Competitive",desc:"عملکرد خوب با ضعف جزئی و قابل مدیریت"},{n:7,fa:"قابل قبول",en:"Acceptable",desc:"ضعف مشخص ولی محدود؛ اقدام بهبود پیشنهاد می‌شود"},{n:6,fa:"مرزی",en:"Borderline",desc:"ضعف مؤثر؛ توضیح و ارائه برنامه اصلاح اجباری است"},{n:5,fa:"حداقل پذیرش",en:"Minimum acceptance",desc:"ریسک فنی یا بازار قابل توجه و نیازمند تصمیم مدیریتی"},{n:4,fa:"ضعیف",en:"Weak",desc:"نقص جدی؛ عبور بدون اصلاح مجاز نیست"},{n:3,fa:"بسیار ضعیف",en:"Very weak",desc:"عملکرد ناپایدار یا نامناسب؛ اصلاح عمده لازم است"},{n:2,fa:"بحرانی",en:"Critical",desc:"نزدیک به عدم عملکرد یا ایجاد ریسک جدی"},{n:1,fa:"تقریباً ناموفق",en:"Almost failed",desc:"عملکرد بسیار محدود و غیرقابل اتکا"}
];
function scorePicker(key,value){return `<div class="scorePicker" role="radiogroup" aria-label="${tr("score")}">${SCORE_LEVELS.map(level=>`<button type="button" class="scoreChoice score-${level.n} ${Number(value)===level.n?"selected":""}" data-score="${key}" data-value="${level.n}" title="${esc(level.desc)}"><strong>${localNumber(level.n)}</strong><small>${locale==="fa"?level.fa:level.en}</small></button>`).join("")}</div>`}
function scoreClass(value){return value?`score-${Number(value)}`:"score-empty"}
function englishTitle(text,kind,id){const match=String(text||"").match(/\(([^()]*[A-Za-z][^()]*)\)/);if(match)return match[1].replace(/\b(ISO)\b/g,"$1").trim();const known={"1":"Safety","2":"Security & Anti-Theft","3":"Body Design, Ergonomics & Packaging","4":"Driving Performance & Dynamics","5":"Powertrain & Energy","6":"Ride, Handling & NVH","7":"Interior Quality & HMI","8":"Electrical Systems & ADAS","9":"Exterior Quality & Lighting","10":"Environmental Performance","11":"Localization & Supply Chain","12":"Product / Process Design Compatibility","13":"Customer Life Cycle & Reliability","14":"Style / Design","15":"Cost / Economics"};return kind==="main"?(known[id]||`Criterion ${id}`):`Assessment Group ${id}`}
const MAIN_TITLES_EN={1:"Safety",2:"Security and Anti-Theft",3:"Body Design, Ergonomics and Packaging",4:"Aerodynamics and Thermal Management",5:"Vehicle Dynamics",6:"Performance and Energy Efficiency",7:"Environmental Protection",8:"Noise, Vibration and Harshness (NVH)",9:"Electrical and Electronic Systems",10:"Cabin Thermal Comfort",11:"Weight and Mass Balance",12:"Design for Manufacturing and Production Process",13:"Customer Life Cycle and Reliability",14:"Styling and Exterior Design",15:"Product Cost and Economics"};
const SUB_TITLES_EN={"1.1":"Active Safety (Braking, Stability and ADAS)","2.1":"Passive Safety (Structure, Seat Belts, Airbags and Pedestrian Impact)","3.1":"Functional Safety of Electronic Systems (ISO 26262)","1.2":"Mechanical and Electronic Anti-Theft Systems","2.2":"Data Protection and Cybersecurity","1.3":"Occupant Space and Accessibility","2.3":"Driver Visibility, Driving Position and Controls","3.3":"Ergonomics and Ease of Entry and Exit","1.4":"Drag Coefficient and Lift Force","2.4":"Powertrain, Battery and Cabin Cooling Performance","3.4":"Thermal Stability under Different Operating Conditions","1.5":"Steering Response, Lateral Stability and Longitudinal Stability","2.5":"Braking, Grip and Handling","3.5":"Suspension and Steering Response","1.6":"Acceleration, Maximum Speed and Traction","2.6":"Fuel or Energy Consumption (WLTP/NEDC)","3.6":"Powertrain Efficiency","1.7":"Gaseous and Particulate Emissions","2.7":"Recyclability and Green Materials","3.7":"Product Life-Cycle and End-of-Life Management","1.8":"Interior and Exterior Noise Levels","2.8":"Body and Steering-Wheel Vibration","3.8":"Acoustic Comfort Assessment","1.9":"Vehicle Electrical Network Stability and Performance","2.9":"Electrical Safety and Energy Management","3.9":"Electromagnetic Compatibility (EMC) Testing","1.10":"Ventilation, Heating and Cooling System Performance","2.10":"Temperature and Airflow Distribution","3.10":"Occupant Thermal Comfort","1.11":"Total Mass and Mass Distribution","2.11":"Effect on Performance and Fuel Consumption","3.11":"Lightweighting Optimization","1.12":"Manufacturability","2.12":"Design Compatibility with Plant Capabilities","3.12":"Assembly Quality Indicators","1.13":"Component Durability and Reliability","2.13":"Serviceability and Maintainability","3.13":"Ownership Experience and Customer Satisfaction","1.14":"Proportions and Brand Design Language","2.14":"Visual Quality and Interior/Exterior Materials","3.14":"Integration of Aesthetics and Function","1.15":"Manufacturing and Material Costs","2.15":"Ownership Cost: Indirect assessment of costs over the ownership life cycle: fuel/energy consumption, depreciation, servicing, and consumable parts.","3.15":"Alignment with Market Positioning and Commercial Targets"};
function localizedTitle(text,kind,id){if(locale==="fa")return clean(String(text||"").replace(/\s*\([^)]*[A-Za-z][^)]*\)\s*/g," "));return kind==="main"?(MAIN_TITLES_EN[id]||englishTitle(text,kind,id)):(SUB_TITLES_EN[id]||englishTitle(text,kind,id))}
function title(text,kind,id){return localizedTitle(text,kind,id)}
const ITEM_TITLES={
  "4.1.1":"عملکرد سامانه‌های ESC و ABS", "4.2.1":"طراحی ایمنی کابین", "5.2.1":"محافظت از عابر پیاده", "4.3.1":"هشدارها و پیام‌های ایمنی",
  "3.1.5":"پایداری در تغییر مسیر سریع", "1.2.6":"بازخورد لحظه‌ای مصرف", "3.1.12":"تلرانس‌های ظاهری و هم‌ترازی قطعات",
  "1.1.13":"کیفیت مواد و مونتاژ", "1.2.15":"مصرف سوخت یا انرژی", "2.2.15":"عمر و دوام قطعات مصرفی",
  "3.2.15":"هزینه‌های سرویس و دسترسی", "2.3.15":"تناسب سطح تجهیز با قیمت هدف",
  "5.1.1":"عملکرد سامانه‌های کمک‌راننده", "1.1.2":"قفل‌ها و دسترسی فیزیکی", "1.2.2":"شفافیت و کنترل تنظیمات کاربر", "3.3.3":"طراحی دسته‌ها و نشیمن",
  "1.2.4":"سامانه‌های خنک‌کننده", "4.1.5":"پایداری طولی", "2.2.5":"رفتار ترمز در پیچ", "3.2.5":"چسبندگی تایرها",
  "4.2.5":"هندلینگ کلی", "1.3.5":"جذب ارتعاش", "3.1.6":"کشش در سربالایی یا بارگذاری", "4.1.6":"حداکثر سرعت قابل‌احساس",
  "1.3.6":"نرمی تعویض دنده", "2.2.7":"استفاده از مواد سبز", "4.2.7":"وزن کلی و مواد سبک", "4.3.7":"راهکار پایان عمر",
  "4.1.8":"نویز باز و بسته‌شدن درب‌ها", "3.3.8":"صدای بسته‌شدن شیشه‌ها و کارکرد تجهیزات", "3.1.10":"واکنش به تغییرات تنظیم دما",
  "4.1.10":"عملکرد تهویه خودکار", "3.2.10":"جهت‌دهی و کنترل دستی جریان هوا", "2.1.11":"واکنش در توقف و شتاب ناگهانی",
  "3.3.11":"کف و اجزای پلاستیکی", "3.2.12":"انطباق طراحی با روش‌های کنترل کیفی", "2.3.12":"صدای بستن درب‌ها و قطعات متحرک",
  "3.3.12":"ثبات قطعات داخل کابین", "2.1.13":"استحکام قطعات متحرک", "2.2.13":"دسترسی به نقاط بازرسی دوره‌ای",
  "4.2.13":"اطلاعات سرویس و دفترچه راهنما", "2.1.14":"همخوانی با زبان طراحی برند", "3.2.14":"دقت مونتاژ تزئینات و درزهای داخلی",
  "2.3.14":"هماهنگی فرم با ارگونومی", "2.1.15":"پیچیدگی مونتاژ", "4.1.15":"تطابق با کلاس قیمتی هدف",
  "1.3.15":"جایگاه محصول نسبت به رقبا", "3.3.15":"ادراک مشتری از ارزش"
};
function itemTitle(item){
  if(item.titleFa)return clean(item.titleFa);
  if(ITEM_TITLES[item.id])return ITEM_TITLES[item.id];
  let plain=clean(item.textFa).replace(/^گام\s*[۰-۹\d]+\.?\s*/,"");
  // The source document usually starts each item with its intended noun-phrase
  // heading, followed by the observation procedure.  Keep only that heading.
  const actionStart=/\s+(?=(?:روی صندلی|خودرو را|موتور را|کولر را|صندلی را|در را|کاپوت را|فرمان را|آینه‌ها را|سطح را|دستانت را|پدال |با سرعت|در سرعت|پس از|هنگام|حین|بدون|از روی|در محیط|در جاده|در هوای|از فاصله|از زاویه|در حالت|بنشین|وارد شو|حرکت کن|حرکت کنید|بررسی کن|بررسی کنید|مشاهده کن|مشاهده کنید|باز کن|باز کنید|روشن کن|روشن کنید|لمس کن|لمس کنید|بران|برو|بده|قرار بده|قرار گیرد|تنظیم کن|تنظیم کنید|نگاه کن|نگاه کنید|امتحان کن|امتحان کنید|تست کن|تست کنید|ارزیابی کن|ارزیابی کنید|بازدید کن|بازدید کنید|بگیر|بگیرید|ببند|ببندید|بچرخان|بچرخانید|فشار بده|فشار دهید|بکش|بکشید|بشمار|بشمارید|لحاظ کن|لحاظ کنید|شبیه‌سازی کن|شبیه‌سازی کنید))/;
  const match=plain.match(actionStart);
  if(match)plain=plain.slice(0,match.index);
  else {const colon=plain.search(/[:؛]/);if(colon>4&&colon<110)plain=plain.slice(0,colon)}
  plain=plain.replace(/\s+(?:را|و|در|از|با)$/," ").trim();
  return plain.length>3?plain:tr("guidance");
}
function instructionBullets(text){
  const description=clean(text);
  return `<div class="instructionBox"><p>${esc(description)}</p></div>`;
}
const EN_ITEM_TITLE={
"1.1.1":"Initial Vehicle Safety Inspection","2.1.1":"Normal Braking Test (Without Instrumentation)","3.1.1":"Maneuvering Stability Test","4.1.1":"Qualitative ESC/ABS Function Test","5.1.1":"ADAS Function Check (If Equipped)","1.2.1":"Body Structure and Door Inspection","2.2.1":"Seat-Belt Inspection","3.2.1":"Airbag System Check (Without Deployment)","4.2.1":"Cabin Safety Design Assessment","5.2.1":"Pedestrian Protection Check","1.3.1":"Warning-Lamp Check at Vehicle Start-Up","2.3.1":"Simple Fault-Condition Simulation","3.3.1":"Basic Fail-Safe System Check","4.3.1":"Safety Warning and Message Assessment",
"1.1.2":"Locks and Physical Access Check","2.1.2":"Engine Immobilizer Check","3.1.2":"Alarm System Assessment","4.1.2":"Interior Equipment Theft-Protection Check","1.2.2":"User-Setting Transparency and Control Check","2.2.2":"Sensitive-Access Control Check","3.2.2":"Personal-Data Protection Check","4.2.2":"Security Warning and Message Assessment",
"1.1.3":"Overall Cabin Spaciousness Assessment","2.1.3":"Front-Seat Space Assessment","3.1.3":"Rear-Seat Space Assessment","4.1.3":"Luggage and Storage Access Check","1.2.3":"Driving Position and Direct Visibility Assessment","2.2.3":"Mirror and Glazing Assessment","3.2.3":"Control and Switchgear Assessment","1.3.3":"Driver Entry Assessment","2.3.3":"Driver and Rear-Passenger Exit Assessment","3.3.3":"Handle and Seat Design Assessment",
"1.1.4":"Aerodynamic Body-Design Inspection","2.1.4":"On-Road Aerodynamic Stability Assessment","1.2.4":"Cooling-System Visual Inspection","2.2.4":"Powertrain Thermal-Performance Check","3.2.4":"Cabin Cooling (HVAC) Assessment","1.3.4":"Sun-Exposure Thermal-Stability Test","2.3.4":"Cold-Condition and Long-Shutdown Behavior Test","3.3.4":"Material Behavior in Hot and Cold Conditions",
"1.1.5":"Straight-Line Stability Assessment","2.1.5":"Cornering Steering-Response Assessment","3.1.5":"Rapid Lane-Change Stability Assessment","4.1.5":"Longitudinal Stability Assessment","1.2.5":"Emergency-Braking Test","2.2.5":"Trail-Braking Behavior Assessment","3.2.5":"Tire-Grip Assessment","4.2.5":"Overall Handling Assessment","1.3.5":"Ride-Comfort Test","2.3.5":"Post-Bump Oscillation Check","3.3.5":"Steering-Feel Assessment",
"1.1.6":"Initial Acceleration Assessment","2.1.6":"Mid-Gear Tractive-Performance Check","3.1.6":"Uphill or Loaded Traction Assessment","4.1.6":"Perceived High-Speed Performance","1.2.6":"Instantaneous Consumption-Feedback Check","2.2.6":"Consumption Assessment Without a Display","3.2.6":"Traffic-Condition Behavior Check","4.2.6":"Energy-Recovery Assessment","1.3.6":"Gearshift Smoothness Check","2.3.6":"Throttle–Transmission Coordination Check","3.3.6":"Constant-Speed Drivetrain Behavior Check","4.3.6":"Powertrain Noise and NVH Integration Check",
"2.1.7":"Visual Exhaust Inspection","3.1.7":"Exhaust-Odor and Engine-Noise Assessment","4.1.7":"Acceleration Smoke Check","5.1.7":"Fluid-Leak and Fuel-Odor Check","1.2.7":"Material-Code Check","2.2.7":"Green-Material Use Assessment","3.2.7":"Modular-Assembly and Disassembly Assessment","4.2.7":"Vehicle Mass and Lightweight-Material Check","1.3.7":"Material Appearance Durability Assessment","2.3.7":"Repairability and Maintainability Check","3.3.7":"Long-Term Assembly-Quality Assessment","4.3.7":"End-of-Life Readiness Assessment",
"1.1.8":"Start-Up and Idle-Noise Check","2.1.8":"Exterior Vehicle-Noise Check","3.1.8":"Noise Assessment at Different Speeds","4.1.8":"Door Opening and Closing Noise Check","1.2.8":"Idle Vibration Check","2.2.8":"Acceleration Vibration Check","3.2.8":"Braking Vibration Check","4.2.8":"Rough-Road Vibration Check","1.3.8":"Cabin Noise Check at Idle","2.3.8":"In-Cabin Conversation Intelligibility Check","3.3.8":"Window and Equipment Noise Check","4.3.8":"Engine-Sound and Vehicle-Speed Coordination Check",
"1.1.9":"Cranking-Voltage Behavior Check","2.1.9":"Full Electrical-Load Test","3.1.9":"System Stability During Mode Transitions","4.1.9":"Charging and Energy-Retention Check","1.2.9":"Cable and Connection Inspection","2.2.9":"Fuse and Power-Distribution Box Check","3.2.9":"Automatic Shutdown and Isolation Safety Test","4.2.9":"Battery-Protection Check","5.2.9":"Low-Voltage System Behavior Check","1.3.9":"Functional Interference (EMI) Check","2.3.9":"Touch and Electronic Switch Check","3.3.9":"Behavior Near External Interference Sources",
"1.1.10":"Air-Conditioning Performance Check","2.1.10":"Heating-Performance Check","3.1.10":"Response to Setting Changes","4.1.10":"Automatic Climate-Control Check","1.2.10":"Front Airflow-Distribution Check","2.2.10":"Rear Temperature-Distribution Check","3.2.10":"Manual Airflow Control Check","1.3.10":"Overall Thermal-Balance Assessment","2.3.10":"HVAC Acoustic-Comfort Assessment","3.3.10":"Direct Airflow Sensation Assessment",
"1.1.11":"Perceived Mass at Launch","2.1.11":"Response to Sudden Stops and Acceleration","3.1.11":"Perceived Mass Over Road Bumps","4.1.11":"Vehicle Mass-Distribution Assessment","5.1.11":"Stability in Gentle Cornering","6.1.11":"Grip During Rapid Direction Changes","1.2.11":"Acceleration and Traction Assessment","2.2.11":"Braking-Behavior Assessment","3.2.11":"Perceived Fuel-Consumption Assessment","1.3.11":"Door and Hood Mass Assessment","2.3.11":"Seat and Interior-Trim Assessment","3.3.11":"Floor and Plastic-Component Assessment",
"1.1.12":"Assembly-Component Simplicity Assessment","2.1.12":"Assembly and Repair Accessibility","3.1.12":"Visible Tolerance and Alignment Check","4.1.12":"Material and Joint Assessment","1.2.12":"Compatibility with Plant Equipment","2.2.12":"Compatibility with Assembly Sequence","3.2.12":"Compatibility with Quality-Control Methods","1.3.12":"Gap and Surface Alignment Check","2.3.12":"Closing-Sound Quality Check","3.3.12":"Cabin-Component Stability Check","4.3.12":"Paint-Surface and Sealing Assessment",
"1.1.13":"Material and Assembly-Quality Inspection","2.1.13":"Moving-Component Strength Check","3.1.13":"Surface-Resistance Assessment","4.1.13":"Perceived Functional-Reliability Assessment","1.2.13":"Consumable-Component Accessibility","2.2.13":"Periodic-Inspection Point Accessibility","3.2.13":"Interior-Component Replacement Assessment","4.2.13":"Service Information and Owner's Manual Check","1.3.13":"Start-Up and Daily-Use Experience","2.3.13":"Driver-Assistance User Experience","3.3.13":"Perceived Door-Closing Solidity",
"1.1.14":"Overall Design-Proportion Assessment","2.1.14":"Brand Design-Language Consistency","3.1.14":"Visual Stance and Character Assessment","1.2.14":"Color Harmony and Surface-Finish Quality","2.2.14":"Interior-Material Functional-Fit Assessment","3.2.14":"Interior-Trim Assembly Accuracy","1.3.14":"Functional-Element Analysis","2.3.14":"Form and Ergonomics Integration","3.3.14":"Overall Design-Coherence Assessment",
"1.1.15":"Visual Material and Component Assessment","2.1.15":"Assembly-Complexity Assessment","3.1.15":"Manufacturing-Process Detail Review","4.1.15":"Target Price-Class Comparison","1.2.15":"Fuel or Energy Consumption Assessment","2.2.15":"Consumable-Component Durability Assessment","3.2.15":"Service-Cost and Accessibility Assessment","4.2.15":"Residual-Value Assessment","1.3.15":"Competitive Product-Position Analysis","2.3.15":"Equipment-Level Fit with Target Price","3.3.15":"Customer Perception of Value"
};
function itemTitleEn(item){return EN_ITEM_TITLE[item.id]||"Vehicle Assessment Item"}
function instructionEnglish(item){return `<div class="instructionBox"><p><strong>${esc(itemTitleEn(item))}:</strong> Carry out the specified inspection or driving check under safe, representative conditions. Observe the vehicle response, record any abnormal behavior or deviation, and then assign the appropriate score.</p></div>`}
const CRITERION_ICONS=[
  '<path d="M12 3l7 3v5c0 4.6-2.8 7.7-7 10-4.2-2.3-7-5.4-7-10V6l7-3z"/><path d="M9 12l2 2 4-5"/>',
  '<rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 018 0v3"/>',
  '<path d="M4 15l2-6h12l2 6"/><path d="M6 15v4m12-4v4M7 15h10M8 9l2-4h4l2 4"/>',
  '<circle cx="12" cy="12" r="8"/><path d="M12 12l4-3M5 15h14"/>',
  '<path d="M13 2L5 14h6l-1 8 9-13h-6z"/>',
  '<path d="M4 12h3l2-5 4 10 2-5h5"/>',
  '<rect x="4" y="5" width="16" height="14" rx="2"/><path d="M8 9h8M8 13h5"/>',
  '<path d="M4 16V8m4 8V5m4 11V9m4 7V4m4 12v-6"/>',
  '<path d="M3 13h18M6 13l2-6h8l2 6M7 17h.01M17 17h.01"/>',
  '<path d="M12 21c4-4 7-7.3 7-12a7 7 0 00-14 0c0 4.7 3 8 7 12z"/><path d="M9 10c2 0 3-1 4-3 1 2 1 4-1 6"/>',
  '<path d="M4 7h16v10H4zM8 7V4h8v3M8 17v3h8v-3"/>',
  '<path d="M4 5h6v6H4zM14 5h6v6h-6zM9 14h6v6H9zM10 8h4M7 11l4 3m6-3l-4 3"/>',
  '<path d="M4 18V6h16v12M7 18v-5h4v5M14 9h3M14 13h3"/>',
  '<path d="M3 17l6-6 4 4 8-9M16 6h5v5"/>',
  '<circle cx="12" cy="12" r="9"/><path d="M15 8h-5a2 2 0 000 4h4a2 2 0 010 4H9m3-10v12"/>'
];
function criterionIcon(index){return `<span class="criterionIcon"><svg viewBox="0 0 24 24" aria-hidden="true">${CRITERION_ICONS[index]||CRITERION_ICONS[0]}</svg></span>`}
function criterionIconForMain(main){const index=window.ASSESSMENT_CRITERIA.findIndex(item=>String(item.id)===String(main?.id));return criterionIcon(index>=0?index:0)}
function mainCounts(main){const total=main.subgroups.reduce((sum,sub)=>sum+sub.items.length,0);return {answered:valuesForMain(main).length,total}}
function renderTabs(){
  $("#criteriaTabs").innerHTML=window.ASSESSMENT_CRITERIA.map((main,index)=>{const count=mainCounts(main);const tail=currentRole==="manager"?`<strong id="tab-score-${main.id}">—</strong>`:`<small class="tabProgress" id="tab-progress-${main.id}">${localNumber(count.answered)} ${locale==="fa"?"از":"of"} ${localNumber(count.total)}</small>`;return `<div class="criterionNavGroup"><button class="criterionTab ${main.id===activeMain?"active":""}" type="button" data-main="${main.id}">${criterionIcon(index)}<span class="criterionName">${title(main.titleFa,"main",main.id)}</span>${tail}</button></div>`}).join("");
  document.querySelectorAll("[data-main]").forEach(el=>el.addEventListener("click",()=>{activeMain=el.dataset.main;renderTabs();renderCriteria();window.scrollTo({top:document.querySelector(".assessmentLayout").offsetTop-18,behavior:"smooth"})}));
}
function renderCriteria(){
  const main=window.ASSESSMENT_CRITERIA.find(x=>x.id===activeMain);
  const groups=main.subgroups.map((sub,index)=>`<details class="subgroup" id="sub-${main.id}-${index}"><summary class="subgroupHead"><h3>${title(sub.titleFa,"sub",sub.id)}</h3><span class="subgroupChevron" aria-hidden="true">⌄</span></summary><div class="subgroupContent">${sub.items.length?sub.items.map(item=>{
    const key=itemKey(main,sub,item);const instructions=locale==="fa"?instructionBullets(item.textFa):instructionEnglish(item);return `<article class="item"><div class="itemText"><div class="itemTitle"><strong>${locale==="fa"?itemTitle(item):itemTitleEn(item)}</strong></div>${instructions}</div><div class="ratingBox">${scorePicker(key,state.scores[key])}</div><details class="notePanel"><summary><span class="notePlus">＋</span><span>${locale==="fa"?"افزودن یادداشت یا تصویر":"Add note or photo"}</span><small data-attachment-count="${key}">${attachmentCountText(key)}</small></summary><div class="noteContent"><label>${tr("notes")}</label><textarea data-note="${key}" placeholder="${tr("placeholder")}">${state.notes[key]||""}</textarea><div class="evidenceActions"><label class="uploadButton"><input type="file" accept="image/*" multiple data-attachment-input="${key}" hidden><span>▧</span>${locale==="fa"?"بارگذاری عکس":"Upload photo"}</label></div><div class="attachmentList" data-attachments="${key}">${renderAttachments(key)}</div></div></details></article>`
  }).join(""):`<p class="empty">${locale==="fa"?"برای این گروه مورد امتیازدهی تعریف نشده است.":"No assessment items are defined for this group."}</p>`}</div></details>`).join("");
  $("#criteria").innerHTML=`<section class="mainCriterion"><div class="mainHead"><div><p>${tr("selected")}</p><h2>${title(main.titleFa,"main",main.id)}</h2></div>${currentRole==="manager"?`<span class="mainScore" id="main-score-${main.id}">— ${tr("outOf")}</span>`:""}</div><div class="mainBody">${groups}</div></section>`;
  document.querySelectorAll("[data-score]").forEach(el=>el.addEventListener("click",e=>{const button=e.currentTarget;state.scores[button.dataset.score]=button.dataset.value;button.closest(".scorePicker").querySelectorAll(".scoreChoice").forEach(x=>x.classList.toggle("selected",x===button));update();persist()}));
  document.querySelectorAll("[data-note]").forEach(el=>el.addEventListener("input",e=>{state.notes[e.target.dataset.note]=e.target.value;persist()}));
  bindAttachmentControls();
  updateMainScore();
}
function attachmentCountText(key){const n=(state.attachments?.[key]||[]).length;return n?`${localNumber(n)} ${locale==="fa"?"فایل":"files"}`:""}
function renderAttachments(key){return (state.attachments?.[key]||[]).map((file,i)=>`<div class="attachment"><span class="attachmentType">${file.type.startsWith("image")?"▧":file.type.startsWith("video")?"▶":"♫"}</span><span title="${esc(file.name)}">${esc(file.name)}</span><button type="button" title="${locale==="fa"?tr("remove"):"Remove"}" data-remove-attachment="${key}|${i}">×</button></div>`).join("")}
function refreshAttachments(key){const out=document.querySelector(`[data-attachments="${CSS.escape(key)}"]`);if(out)out.innerHTML=renderAttachments(key);const count=document.querySelector(`[data-attachment-count="${CSS.escape(key)}"]`);if(count)count.textContent=attachmentCountText(key)}
function addFiles(key,files){const list=Array.from(files||[]);if(!list.length)return;state.attachments=state.attachments||{};const allowed=list.filter(f=>/^image\//.test(f.type));if(allowed.some(f=>f.size>8*1024*1024)){alert(locale==="fa"?tr("attachmentLimit"):"For offline performance, each file must be 8 MB or smaller.");return}Promise.all(allowed.map(file=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve({name:file.name,type:file.type,size:file.size,data:r.result});r.readAsDataURL(file)}))).then(filesData=>{state.attachments[key]=[...(state.attachments[key]||[]),...filesData];refreshAttachments(key);persist()})}
function removeAttachment(key,index){state.attachments[key].splice(index,1);if(!state.attachments[key].length)delete state.attachments[key];refreshAttachments(key);persist()}
function recordAudio(key,button){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){alert(locale==="fa"?"ضبط صدا در این مرورگر پشتیبانی نمی‌شود؛ لطفاً فایل صوتی را بارگذاری کنید.":"Audio recording is not supported by this browser. Please upload an audio file.");return}navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{const rec=new MediaRecorder(stream);const chunks=[];rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:rec.mimeType||"audio/webm"});if(blob.size>8*1024*1024){alert(locale==="fa"?tr("attachmentLimit"):"For offline performance, each file must be 8 MB or smaller.");return}const r=new FileReader();r.onload=()=>{state.attachments=state.attachments||{};state.attachments[key]=[...(state.attachments[key]||[]),{name:`voice-note-${new Date().toLocaleTimeString().replace(/[: ]/g,"-")}.webm`,type:blob.type,size:blob.size,data:r.result}];refreshAttachments(key);persist()};r.readAsDataURL(blob)};rec.start();button.textContent="■ "+(locale==="fa"?tr("stopRecording"):"Stop recording");button.classList.add("recording");button.onclick=()=>rec.stop();rec.onstop=()=>{button.textContent="● "+(locale==="fa"?tr("recordVoice"):"Record voice");button.classList.remove("recording");button.onclick=()=>recordAudio(key,button)}}).catch(()=>alert(locale==="fa"?"دسترسی به میکروفون داده نشد.":"Microphone access was not granted."))}
function bindAttachmentControls(){document.querySelectorAll("[data-attachment-input]").forEach(el=>el.addEventListener("change",e=>{addFiles(e.target.dataset.attachmentInput,e.target.files);e.target.value=""}));document.querySelectorAll("[data-remove-attachment]").forEach(el=>el.addEventListener("click",()=>{const [key,index]=el.dataset.removeAttachment.split("|");removeAttachment(key,Number(index))}))}
const VEHICLE_PHOTO_VIEWS=[{key:"front",label:"frontView"},{key:"rear",label:"rearView"},{key:"left",label:"leftView"},{key:"right",label:"rightView"}];
const activeVehiclePhoto={evaluator:"front",manager:"front"};
function selectedVehicleView(mode){const current=activeVehiclePhoto[mode];if(VEHICLE_PHOTO_VIEWS.some(view=>view.key===current))return current;return VEHICLE_PHOTO_VIEWS.find(view=>state.vehiclePhotos?.[view.key])?.key||"front"}
function vehiclePhotoMarkup(mode){const manager=mode==="manager",activeKey=selectedVehicleView(mode),activeView=VEHICLE_PHOTO_VIEWS.find(view=>view.key===activeKey),photo=state.vehiclePhotos?.[activeKey];return `<div class="vehicleGallery" data-gallery-mode="${mode}"><div class="vehicleGalleryStage"><div class="vehicleGalleryImage">${photo?`<img src="${photo.data}" alt="${tr(activeView.label)}">`:`<div class="vehicleGalleryEmpty"><strong>${tr(activeView.label)}</strong><span>${tr("noVehiclePhoto")}</span></div>`}</div><div class="vehicleGalleryCaption"><strong>${tr(activeView.label)}</strong>${manager?"":`<div class="vehiclePhotoActions"><label class="vehiclePhotoButton"><input type="file" accept="image/*" data-vehicle-photo="${activeKey}" hidden>${photo?tr("changeVehiclePhoto"):tr("addVehiclePhoto")}</label>${photo?`<button class="vehiclePhotoRemove" type="button" data-remove-vehicle-photo="${activeKey}">${tr("remove")}</button>`:""}</div>`}</div></div><div class="vehicleGalleryThumbs" role="tablist" aria-label="${tr("vehiclePhotosTitle")}">${VEHICLE_PHOTO_VIEWS.map(view=>{const item=state.vehiclePhotos?.[view.key],selected=view.key===activeKey;return `<button type="button" class="vehicleGalleryThumb ${selected?"isActive":""} ${item?"hasPhoto":""}" data-select-vehicle-photo="${mode}|${view.key}" role="tab" aria-selected="${selected}" title="${tr(view.label)}">${item?`<img src="${item.data}" alt="${tr(view.label)}">`:`<span>${tr(view.label)}</span>`}</button>`}).join("")}</div></div>`}
function renderVehiclePhotos(){document.querySelectorAll("[data-vehicle-photo-grid]").forEach(grid=>grid.innerHTML=vehiclePhotoMarkup(grid.dataset.vehiclePhotoGrid));bindVehiclePhotoControls()}
function optimizeVehiclePhoto(file){return new Promise((resolve,reject)=>{if(!file||!/^image\//.test(file.type))return reject(new Error("invalid"));if(file.size>8*1024*1024)return reject(new Error("size"));const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);resolve({name:file.name,type:"image/jpeg",data:canvas.toDataURL("image/jpeg",.82)})};img.src=reader.result};reader.readAsDataURL(file)})}
function bindVehiclePhotoControls(){document.querySelectorAll("[data-select-vehicle-photo]").forEach(button=>button.addEventListener("click",()=>{const [mode,key]=button.dataset.selectVehiclePhoto.split("|");activeVehiclePhoto[mode]=key;renderVehiclePhotos()}));document.querySelectorAll("[data-vehicle-photo]").forEach(input=>input.addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;try{state.vehiclePhotos=state.vehiclePhotos||{};state.vehiclePhotos[e.target.dataset.vehiclePhoto]=await optimizeVehiclePhoto(file);persist();renderVehiclePhotos()}catch(err){alert(err.message==="size"?tr("attachmentLimit"):(locale==="fa"?"فایل انتخاب‌شده تصویر معتبر نیست.":"The selected file is not a valid image."))}}));document.querySelectorAll("[data-remove-vehicle-photo]").forEach(button=>button.addEventListener("click",()=>{delete state.vehiclePhotos[button.dataset.removeVehiclePhoto];persist();renderVehiclePhotos()}))}
function valuesForMain(main){return main.subgroups.flatMap(sub=>sub.items.map(item=>Number(state.scores[itemKey(main,sub,item)])).filter(Boolean))}
function decision(score){const en=locale==="en";if(!Number.isFinite(score))return[en?"Not assessed":"ارزیابی نشده",en?"Unanswered items are not treated as zero.":"نمره‌های خالی صفر محسوب نمی‌شوند.",""];const s=score*10;if(s>=85)return[en?"Preliminary pass":"عبور مقدماتی",en?"Proceed to economic assessment, industrialization feasibility, and subsequent approvals.":"ورود به ارزیابی‌های اقتصادی، امکان‌سنجی صنعتی‌سازی و تأییدهای بعدی","green"];if(s>=75)return[en?"Conditional pass":"عبور مشروط",en?"Continue after a corrective plan and re-verification of weaknesses.":"ادامه بررسی پس از ارائه برنامه اصلاحی و تأیید مجدد ضعف‌ها","amber"];if(s>=65)return[en?"Revise and reassess":"اصلاح و ارزیابی مجدد",en?"Pause until technical corrections are implemented.":"توقف فرایند تا اجرای اصلاحات فنی","amber"];return[en?"Preliminary rejection":"رد در ارزیابی مقدماتی",en?"Further localization assessment is not recommended.":"عدم توصیه برای ادامه فرایند داخلی‌سازی","red"]}
function updateMainScore(){const main=window.ASSESSMENT_CRITERIA.find(x=>x.id===activeMain);const vals=valuesForMain(main);const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:NaN;const out=$("#main-score-"+activeMain);if(out)out.textContent=fmt(avg)+" "+tr("outOf")}
function renderChart(rows){const ranked=[...rows].filter(r=>Number.isFinite(r.avg)).sort((a,b)=>b.avg-a.avg);const empty=locale==="fa"?"پس از ثبت امتیازها، نمودار مقایسه‌ای در این بخش نمایش داده می‌شود.":"The comparative chart will appear after scores are recorded.";return $("#scoreChart").innerHTML=ranked.length?ranked.map((r,i)=>`<div class="barItem"><div class="barValue">${fmt(r.avg*10)}</div><div class="barTrack"><i style="height:${r.avg/10*100}%;--bar:${['#2463a5','#b54d66','#128778','#d58a24','#7454b8','#d9673a','#3e8c47','#ad5f99','#2c7d9a','#96733c','#5475b5','#b85c48','#4b9a91','#8f5c6b','#527e50'][i%15]}"></i></div><div class="barLabel"><span>${title(r.main.titleFa,"main",r.main.id)}</span></div></div>`).join(""):`<p class="chartEmpty">${empty}</p>`}
function renderQualityChart(){const values=Object.values(state.scores).map(Number).filter(Boolean);const counts=[1,2,3,4,5,6,7,8,9,10].map(n=>values.filter(v=>v===n).length);const total=Math.max(1,...counts);const empty=locale==="fa"?"با ثبت امتیاز، توزیع کیفیت در این بخش نمایش داده می‌شود.":"The quality distribution will appear after scores are recorded.";$("#qualityChart").innerHTML=values.length?counts.map((count,i)=>`<div class="qualityBar"><div class="qualityCount">${localNumber(count)}</div><div class="qualityTrack"><i style="height:${count/total*100}%;--quality-color:${scoreColor(i+1)}"></i></div><strong>${localNumber(i+1)}</strong><span>${locale==="fa"?SCORE_LEVELS.find(x=>x.n===i+1).fa:SCORE_LEVELS.find(x=>x.n===i+1).en}</span></div>`).join(""):`<p class="qualityEmpty">${empty}</p>`}
function scoreColor(n){return ["#9b0b25","#c61f34","#d9462b","#e66a1b","#ef921d","#dbae00","#9fbd33","#36aa63","#07834d","#00663b"][n-1]}
const SCORE_DESCRIPTIONS_EN=["Almost no functional performance; unreliable and unacceptable.","Near-functional failure or a serious risk condition.","Unstable or unsuitable performance; major correction is required.","Serious defect; acceptance is not permitted without correction.","Significant technical or market risk requiring management review.","Material weakness; explanation and a corrective-action plan are mandatory.","Clear but limited weakness; improvement action is recommended.","Good performance with a minor, manageable weakness.","Negligible defect with no perceptible effect on function or customer experience.","Exceeds expectations; no observable or measurable defect."];
function renderScoreGuide(){const guide=$("#scoreGuideGrid");if(!guide)return;guide.innerHTML=SCORE_LEVELS.map(level=>`<article class="guideLevel score-${level.n}"><div><strong style="background:${scoreColor(level.n)}">${localNumber(level.n)}</strong><b>${locale==="fa"?level.fa:level.en}</b></div><p>${locale==="fa"?level.desc:SCORE_DESCRIPTIONS_EN[level.n-1]}</p></article>`).join("")}
function completionHeat(percent){
  const p=Math.max(0,Math.min(100,Number(percent)||0));
  const stops=[[0,[155,11,37]],[33,[217,70,43]],[66,[219,174,0]],[100,[0,102,59]]];
  let left=stops[0],right=stops[stops.length-1];
  for(let i=1;i<stops.length;i++){if(p<=stops[i][0]){left=stops[i-1];right=stops[i];break}}
  const ratio=(p-left[0])/(right[0]-left[0]||1);
  const rgb=left[1].map((value,index)=>Math.round(value+(right[1][index]-value)*ratio));
  return {solid:`rgb(${rgb.join(",")})`,soft:`rgba(${rgb.join(",")},.13)`};
}
function update(){
  const criteriaCount=window.ASSESSMENT_CRITERIA.length;
  const rawConfiguredWeights=window.ASSESSMENT_CRITERIA.map(main=>{const w=Number(state.weights[main.id]??(1/criteriaCount));return Number.isFinite(w)&&w>=0?w:0});
  const rawWeightTotal=rawConfiguredWeights.reduce((sum,weight)=>sum+weight,0);
  const configuredWeights=rawWeightTotal>0?rawConfiguredWeights.map(weight=>weight/rawWeightTotal):window.ASSESSMENT_CRITERIA.map(()=>1/criteriaCount);
  const configuredWeightTotal=configuredWeights.reduce((sum,weight)=>sum+weight,0);
  let scored=0;
  const rows=window.ASSESSMENT_CRITERIA.map((main,index)=>{const vals=valuesForMain(main);const counts=mainCounts(main);scored+=vals.length;const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:NaN;const avg100=Number.isFinite(avg)?avg*10:NaN;const weight=configuredWeights[index];const weightedContribution=Number.isFinite(avg100)&&Number.isFinite(weight)?avg100*weight:NaN;const completion=counts.total?counts.answered/counts.total*100:0;return {main,avg,avg100,weight,ws:weightedContribution,final100:weightedContribution,completion,answered:counts.answered,total:counts.total}});
  const completedRows=rows.filter(row=>Number.isFinite(row.final100)&&Number.isFinite(row.weight));
  const completedWeight=completedRows.reduce((sum,row)=>sum+row.weight,0);
  const final100=completedWeight>0?completedRows.reduce((sum,row)=>sum+row.final100,0)/completedWeight:NaN;
  const final=Number.isFinite(final100)?final100/10:NaN,totalItems=window.ASSESSMENT_CRITERIA.flatMap(m=>m.subgroups.flatMap(s=>s.items)).length;
  const percent=totalItems?Math.round(scored/totalItems*100):0;$("#finalScore").textContent=fmt(Number.isFinite(final)?final*10:NaN);$("#completionText").textContent=locale==="fa"?`${localNumber(scored)} از ${localNumber(totalItems)}`:`${localNumber(scored)} of ${localNumber(totalItems)}`;$("#progressBar").style.width=`${percent}%`;$("#evaluatorCompletionPercent").textContent=`${localNumber(percent)}٪`;$("#evaluatorCompletionText").textContent=locale==="fa"?`${localNumber(scored)} از ${localNumber(totalItems)} پاسخ`:`${localNumber(scored)} of ${localNumber(totalItems)} answered`;$("#evaluatorProgressBar").style.width=`${percent}%`;
  const [verdict,hint,color]=decision(final);$("#verdict").textContent=verdict;$("#verdictHint").textContent=hint;$("#verdict").style.color=`var(--${color||'text'})`;
  const accents=['#2463a5','#b54d66','#128778','#d58a24','#7454b8','#d9673a','#3e8c47','#ad5f99','#2c7d9a','#96733c','#5475b5','#b85c48','#4b9a91','#8f5c6b','#527e50'];
  const h=locale==="fa"?["ردیف","آیکون","شاخص","میانگین از ۱۰","وزن","سهم در امتیاز کل","نرخ تکمیل"]:["No.","Icon","Criterion","Average / 10","Weight","Contribution / 100","Completion"];
  const notRated=locale==="fa"?"ارزیابی نشده":"Not assessed";
  $("#summaryBody").innerHTML=`<div class="integratedSummaryHead">${h.map(x=>`<span>${x}</span>`).join("")}</div>${rows.map((r,index)=>{const heat=completionHeat(r.completion);const pct=Math.round(r.completion);return `<article class="integratedSummaryRow" style="--row-accent:${accents[index]};--completion-color:${heat.solid};--completion-soft:${heat.soft};--completion-percent:${pct}%"><span class="integratedRowNumber">${localNumber(index+1)}</span><span class="integratedIcon">${criterionIconForMain(r.main)}</span><strong>${title(r.main.titleFa,"main",r.main.id)}</strong><span class="integratedScore">${Number.isFinite(r.avg)?fmt(r.avg):notRated}</span><span class="integratedWeight">${localNumber(Number(r.weight).toFixed(3))}</span><span class="integratedFinal">${Number.isFinite(r.final100)?fmt(r.final100):notRated}</span><span class="integratedCompletion"><span class="completionVisual"><b>${localNumber(pct)}٪</b><span class="completionMeter" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${pct}"><i aria-hidden="true"></i></span></span><small>${locale==="fa"?`${localNumber(r.answered)} از ${localNumber(r.total)}`:`${localNumber(r.answered)} of ${localNumber(r.total)}`}</small></span></article>`}).join("")}`;
  $("#summaryFinal").textContent=fmt(Number.isFinite(final)?final*10:NaN);
  rows.forEach(r=>{const out=$("#tab-score-"+r.main.id);if(out)out.textContent=fmt(r.avg);const progress=$("#tab-progress-"+r.main.id);if(progress){const count=mainCounts(r.main);progress.textContent=`${localNumber(count.answered)} ${locale==="fa"?"از":"of"} ${localNumber(count.total)}`;progress.classList.toggle("complete",count.answered===count.total)}});renderChart(rows);renderQualityChart();updateMainScore();if(window.managerRefresh)window.managerRefresh(rows,final,percent);
}
function persist(){localStorage.setItem("bamco-vehicle-assessment",JSON.stringify(state));const status=$("#autosaveStatus");if(status){status.textContent=tr("saved");setTimeout(()=>{if(status.isConnected)status.textContent=tr("ready")},800)}}
const PERSIAN_MONTHS_FA=["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"];
const PERSIAN_MONTHS_EN=["Farvardin","Ordibehesht","Khordad","Tir","Mordad","Shahrivar","Mehr","Aban","Azar","Dey","Bahman","Esfand"];
function isoLocal(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function persianParts(value){const date=value instanceof Date?value:new Date(`${value||isoLocal(new Date())}T12:00:00`);const parts=new Intl.DateTimeFormat("en-US-u-ca-persian",{year:"numeric",month:"numeric",day:"numeric"}).formatToParts(date);const out={};parts.forEach(p=>{if(p.type==="year"||p.type==="month"||p.type==="day")out[p.type]=Number(p.value)});return {jy:out.year,jm:out.month,jd:out.day}}
function gregorianFromPersian(jy,jm,jd){const start=new Date(jy+621,1,20,12);for(let i=0;i<410;i++){const d=new Date(start);d.setDate(start.getDate()+i);const p=persianParts(d);if(p.jy===jy&&p.jm===jm&&p.jd===jd)return d}return null}
function formatAssessmentDate(value,fa=locale==="fa"){if(!value)return "";const p=persianParts(value);const plain=`${p.jy}/${String(p.jm).padStart(2,"0")}/${String(p.jd).padStart(2,"0")}`;return fa?faNum(plain):plain}
function closeJalaliCalendar(){document.querySelector(".jalaliCalendarOverlay")?.remove()}
function openJalaliCalendar(input){closeJalaliCalendar();let shown=persianParts(state.metadata.date);const overlay=document.createElement("div");overlay.className="jalaliCalendarOverlay";overlay.innerHTML='<div class="jalaliCalendar" role="dialog" aria-modal="true"></div>';document.body.appendChild(overlay);const panel=overlay.firstElementChild;
  const draw=()=>{const first=gregorianFromPersian(shown.jy,shown.jm,1);const next=shown.jm===12?gregorianFromPersian(shown.jy+1,1,1):gregorianFromPersian(shown.jy,shown.jm+1,1);const days=Math.round((next-first)/86400000);const selected=persianParts(state.metadata.date);const week=locale==="fa"?["ش","ی","د","س","چ","پ","ج"]:["Sa","Su","Mo","Tu","We","Th","Fr"];const month=(locale==="fa"?PERSIAN_MONTHS_FA:PERSIAN_MONTHS_EN)[shown.jm-1];const lead=(first.getDay()+1)%7;panel.innerHTML=`<div class="jalaliCalendarHead"><button type="button" data-cal-next aria-label="${locale==="fa"?"ماه بعد":"Next month"}">‹</button><strong>${month} ${localNumber(shown.jy)}</strong><button type="button" data-cal-prev aria-label="${locale==="fa"?"ماه قبل":"Previous month"}">›</button></div><div class="jalaliWeek">${week.map(x=>`<span>${x}</span>`).join("")}</div><div class="jalaliDays">${"<span></span>".repeat(lead)}${Array.from({length:days},(_,i)=>{const day=i+1,isSelected=selected.jy===shown.jy&&selected.jm===shown.jm&&selected.jd===day;return `<button type="button" class="${isSelected?"selected":""}" data-jday="${day}">${localNumber(day)}</button>`}).join("")}</div><div class="jalaliCalendarFoot"><button type="button" data-cal-today>${locale==="fa"?"امروز":"Today"}</button><button type="button" data-cal-close>${locale==="fa"?"بستن":"Close"}</button></div>`;panel.querySelector("[data-cal-prev]").onclick=()=>{shown.jm--;if(shown.jm<1){shown.jm=12;shown.jy--}draw()};panel.querySelector("[data-cal-next]").onclick=()=>{shown.jm++;if(shown.jm>12){shown.jm=1;shown.jy++}draw()};panel.querySelectorAll("[data-jday]").forEach(btn=>btn.onclick=()=>{const d=gregorianFromPersian(shown.jy,shown.jm,Number(btn.dataset.jday));state.metadata.date=isoLocal(d);input.value=formatAssessmentDate(state.metadata.date);persist();update();closeJalaliCalendar()});panel.querySelector("[data-cal-today]").onclick=()=>{state.metadata.date=isoLocal(new Date());input.value=formatAssessmentDate(state.metadata.date);persist();update();closeJalaliCalendar()};panel.querySelector("[data-cal-close]").onclick=closeJalaliCalendar};draw();overlay.addEventListener("click",e=>{if(e.target===overlay)closeJalaliCalendar()})}
function openJalaliCalendarFor(input,currentValue,onSelect){
  closeJalaliCalendar();let selectedValue=currentValue||isoLocal(new Date()),shown=persianParts(selectedValue);const overlay=document.createElement("div");overlay.className="jalaliCalendarOverlay";overlay.innerHTML='<div class="jalaliCalendar" role="dialog" aria-modal="true"></div>';document.body.appendChild(overlay);const panel=overlay.firstElementChild;
  const choose=date=>{selectedValue=isoLocal(date);input.value=formatAssessmentDate(selectedValue);onSelect(selectedValue);closeJalaliCalendar()};
  const draw=()=>{const first=gregorianFromPersian(shown.jy,shown.jm,1),next=shown.jm===12?gregorianFromPersian(shown.jy+1,1,1):gregorianFromPersian(shown.jy,shown.jm+1,1),days=Math.round((next-first)/86400000),selected=persianParts(selectedValue),week=locale==="fa"?["ش","ی","د","س","چ","پ","ج"]:["Sa","Su","Mo","Tu","We","Th","Fr"],month=(locale==="fa"?PERSIAN_MONTHS_FA:PERSIAN_MONTHS_EN)[shown.jm-1],lead=(first.getDay()+1)%7;panel.innerHTML=`<div class="jalaliCalendarHead"><button type="button" data-cal-next aria-label="${locale==="fa"?"ماه بعد":"Next month"}">‹</button><strong>${month} ${localNumber(shown.jy)}</strong><button type="button" data-cal-prev aria-label="${locale==="fa"?"ماه قبل":"Previous month"}">›</button></div><div class="jalaliWeek">${week.map(x=>`<span>${x}</span>`).join("")}</div><div class="jalaliDays">${"<span></span>".repeat(lead)}${Array.from({length:days},(_,i)=>{const day=i+1,isSelected=selected.jy===shown.jy&&selected.jm===shown.jm&&selected.jd===day;return `<button type="button" class="${isSelected?"selected":""}" data-jday="${day}">${localNumber(day)}</button>`}).join("")}</div><div class="jalaliCalendarFoot"><button type="button" data-cal-today>${locale==="fa"?"امروز":"Today"}</button><button type="button" data-cal-close>${locale==="fa"?"بستن":"Close"}</button></div>`;panel.querySelector("[data-cal-prev]").onclick=()=>{shown.jm--;if(shown.jm<1){shown.jm=12;shown.jy--}draw()};panel.querySelector("[data-cal-next]").onclick=()=>{shown.jm++;if(shown.jm>12){shown.jm=1;shown.jy++}draw()};panel.querySelectorAll("[data-jday]").forEach(btn=>btn.onclick=()=>choose(gregorianFromPersian(shown.jy,shown.jm,Number(btn.dataset.jday))));panel.querySelector("[data-cal-today]").onclick=()=>choose(new Date());panel.querySelector("[data-cal-close]").onclick=closeJalaliCalendar};draw();overlay.addEventListener("click",e=>{if(e.target===overlay)closeJalaliCalendar()})
}
window.openJalaliCalendarFor=openJalaliCalendarFor;
function renderMetadata(){document.querySelectorAll("[data-meta]").forEach(el=>{const key=el.dataset.meta,value=state.metadata[key]||"";el.value=key==="date"?formatAssessmentDate(state.metadata.date):(el.dataset.localizedNumber&&locale==="fa"?faNum(value):value);if(el.dataset.bound)return;el.dataset.bound="1";if(key==="date"){el.addEventListener("click",()=>openJalaliCalendar(el));el.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openJalaliCalendar(el)}})}else el.addEventListener("input",e=>{if(e.target.dataset.localizedNumber&&locale==="fa")e.target.value=faNum(e.target.value);state.metadata[e.target.dataset.meta]=e.target.value;persist()})})}
function englishFileToken(value,fallback="vehicle"){
  const ascii=String(value||"").normalize("NFKD").replace(/[^\x00-\x7F]/g,"").replace(/[^A-Za-z0-9._-]+/g,"_").replace(/^_+|_+$/g,"");
  return ascii||fallback;
}
window.englishFileToken=englishFileToken;
function download(){const blob=new Blob([JSON.stringify({version:2,savedAt:new Date().toISOString(),state},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`vehicle_assessment_${englishFileToken(state.metadata.model,"vehicle")}.json`;a.click();URL.revokeObjectURL(a.href)}
function esc(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function persianCriterionName(main){return clean(main?.titleFa||"").replace(/\([^)]*[A-Za-z][^)]*\)/g,"").replace(/[A-Za-z][A-Za-z0-9&/\-–—., ]*/g,"").replace(/[\s\/\-–—]+$/g,"").replace(/\s+/g," ").trim()}
function excelImagePayload(photo){
  if(!photo||!photo.data)return null;
  const data=String(photo.data||"");
  const m=data.match(/^data:image\/([^;]+);base64,(.*)$/i);
  const mime=String(photo.type||m?.[1]||"jpeg").toLowerCase();
  const extension=mime.includes("png")?"png":mime.includes("gif")?"gif":"jpeg";
  const base64=m?m[2]:data.replace(/^data:[^,]+,/,"");
  return base64?{base64,extension}:null;
}
function addVehicleViewsWorksheet(wb,photos,fa=true){
  const txt=(a,b)=>fa?a:b;
  const ws=wb.addWorksheet(txt("چهار نمای خودرو","Four Vehicle Views"));
  ws.views=[{rightToLeft:fa,showGridLines:false}];ws.properties.defaultRowHeight=20;
  ws.mergeCells("A1:H1");ws.getCell("A1").value=txt("چهار نمای خودرو","Four Vehicle Views");
  ws.getCell("A1").font={bold:true,size:17,color:{argb:"FFFFFFFF"}};ws.getCell("A1").fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF163B69"}};ws.getCell("A1").alignment={horizontal:"center",vertical:"middle"};ws.getRow(1).height=32;
  for(let c=1;c<=8;c++)ws.getColumn(c).width=16;
  const views=[
    ["front",txt("نمای جلو","Front View"),1,3],["rear",txt("نمای عقب","Rear View"),5,3],
    ["left",txt("نمای چپ","Left View"),1,22],["right",txt("نمای راست","Right View"),5,22]
  ];
  views.forEach(([key,label,col,row])=>{
    ws.mergeCells(row,col,row,col+3);const head=ws.getCell(row,col);head.value=label;head.font={bold:true,color:{argb:"FF244B70"}};head.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFEAF3F8"}};head.alignment={horizontal:"center",vertical:"middle"};ws.getRow(row).height=25;
    const photo=photos?.[key],payload=excelImagePayload(photo);
    if(payload){
      try{const id=wb.addImage(payload);ws.addImage(id,{tl:{col:col-1+.08,row:row+.35},ext:{width:410,height:245}})}catch(_){ws.mergeCells(row+1,col,row+15,col+3);ws.getCell(row+1,col).value=txt("درج تصویر ناموفق بود.","The image could not be embedded.")}
    }else{ws.mergeCells(row+1,col,row+15,col+3);const cell=ws.getCell(row+1,col);cell.value=txt("عکسی ثبت نشده است.","No photo recorded.");cell.alignment={horizontal:"center",vertical:"middle"};cell.font={italic:true,color:{argb:"FF7A8C9B"}};cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFF8FAFC"}}}
    for(let rr=row+1;rr<=row+15;rr++)ws.getRow(rr).height=18;
  });
  ws.pageSetup={orientation:"landscape",fitToPage:true,fitToWidth:1,fitToHeight:1,paperSize:9};
  return ws;
}
window.addVehicleViewsWorksheet=addVehicleViewsWorksheet;

async function exportExcel(){
  if(!window.ExcelJS){alert(locale==="fa"?"ماژول خروجی اکسل بارگذاری نشد؛ لطفاً برنامه را از داخل فایل فشرده استخراج و دوباره باز کنید.":"The Excel export module did not load. Extract the ZIP and reopen the app.");return}
  const fa=locale==="fa",txt=(a,b)=>fa?a:b;
  const evaluatorCommentInput=document.querySelector('[data-final-comment="evaluator"]');
  if(evaluatorCommentInput){state.finalComments=state.finalComments||{};state.finalComments.evaluator=evaluatorCommentInput.value||"";if(typeof persist==="function")persist()}
  const rows=window.ASSESSMENT_CRITERIA.map(main=>{const vals=valuesForMain(main);const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:NaN;return {main,avg}});
  const criterionName=main=>fa?persianCriterionName(main):title(main.titleFa,"main",main.id);
  const wb=new ExcelJS.Workbook();wb.creator="BAMCO Vehicle Assessment";wb.created=new Date();
  const styleHeader=row=>{row.eachCell(cell=>{cell.font={bold:true,color:{argb:"FFFFFFFF"}};cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF163B69"}};cell.alignment={horizontal:"center",vertical:"middle",wrapText:true};cell.border={bottom:{style:"thin",color:{argb:"FFD4DFEA"}}}})};
  const setSheet=ws=>{ws.views=[{rightToLeft:fa,showGridLines:false}];ws.properties.defaultRowHeight=21;};
  const report=wb.addWorksheet(txt("گزارش ارزیابی","Assessment Report"));setSheet(report);report.mergeCells("A1:C1");report.getCell("A1").value=txt("گزارش ارزیابی خودرو","Vehicle Assessment Report");report.getCell("A1").font={bold:true,size:16,color:{argb:"FF163B69"}};report.getCell("A1").alignment={horizontal:"center"};
  const metaRows=[
    [txt("نام ارزیاب","Evaluator Name"),state.metadata.evaluator],[txt("سابقه کاری ارزیاب","Evaluator Work Experience"),window.getEvaluatorExperienceDisplay?window.getEvaluatorExperienceDisplay(fa?"fa":"en"):state.metadata.evaluatorExperience],
    [txt("شماره تماس ارزیاب","Evaluator Phone"),state.metadata.evaluatorPhone],[txt("ایمیل ارزیاب","Evaluator Email"),state.metadata.evaluatorEmail],[txt("تاریخ ارزیابی","Assessment Date"),formatAssessmentDate(state.metadata.date,true)],
    [txt("برند خودرو","Vehicle Make"),state.metadata.brand],[txt("مدل خودرو","Vehicle Model"),state.metadata.model],[txt("شماره شاسی خودرو","VIN"),state.metadata.vin],[txt("کارکرد (کیلومتر)","Odometer (km)"),state.metadata.odometer]
  ];
  metaRows.forEach((x,i)=>{report.getCell(i+3,1).value=x[0];report.getCell(i+3,2).value=x[1]||"";report.getCell(i+3,1).font={bold:true};});
  const commentLabelRow=13;report.getCell(commentLabelRow,1).value=txt("نظر نهایی ارزیاب","Evaluator Final Comment");report.getCell(commentLabelRow,1).font={bold:true,color:{argb:"FF244B70"}};report.getCell(commentLabelRow,1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFEAF3F8"}};
  report.mergeCells(`A${commentLabelRow+1}:C${commentLabelRow+3}`);const commentCell=report.getCell(commentLabelRow+1,1);commentCell.value=state.finalComments?.evaluator||"";commentCell.alignment={vertical:"top",horizontal:fa?"right":"left",wrapText:true};commentCell.border={top:{style:"thin",color:{argb:"FFD8E3EA"}},bottom:{style:"thin",color:{argb:"FFD8E3EA"}},left:{style:"thin",color:{argb:"FFD8E3EA"}},right:{style:"thin",color:{argb:"FFD8E3EA"}}};
  [commentLabelRow+1,commentLabelRow+2,commentLabelRow+3].forEach(r=>report.getRow(r).height=24);
  report.addRow([]);const summaryHead=report.addRow([txt("کد","Code"),txt("شاخص","Criterion"),txt("میانگین از ۱۰","Average / 10")]);styleHeader(summaryHead);rows.forEach(r=>report.addRow([r.main.id,criterionName(r.main),Number.isFinite(r.avg)?Number(r.avg.toFixed(2)):""]));report.columns=[{width:11},{width:52},{width:16}];
  const details=wb.addWorksheet(txt("ریز ارزیابی","Assessment Details"));setSheet(details);const detailsHead=details.addRow([txt("کد شاخص","Criterion Code"),txt("شاخص","Criterion"),txt("کد زیرشاخص","Subcriterion Code"),txt("زیرشاخص","Subcriterion"),txt("کد آیتم","Item Code"),txt("نام آیتم","Item"),txt("امتیاز","Score"),txt("یادداشت ارزیاب","Evaluator Note"),txt("تعداد مستندات","Evidence Count")]);styleHeader(detailsHead);
  window.ASSESSMENT_CRITERIA.forEach(main=>main.subgroups.forEach(sub=>sub.items.forEach(item=>{const key=itemKey(main,sub,item);details.addRow([main.id,criterionName(main),sub.id,fa?clean(sub.titleFa):title(sub.titleFa,"sub",sub.id),item.id,fa?(item.titleFa||itemTitle(item)):itemTitleEn(item),state.scores[key]||"",state.notes[key]||"",(state.attachments[key]||[]).length])})));details.columns=[{width:12},{width:30},{width:14},{width:34},{width:13},{width:35},{width:11},{width:48},{width:14}];details.getColumn(8).alignment={wrapText:true,vertical:"top"};details.autoFilter={from:"A1",to:"I1"};
  const evidence=wb.addWorksheet(txt("مستندات","Evidence"));setSheet(evidence);const evidenceHead=evidence.addRow([txt("کد آیتم","Item Code"),txt("نام آیتم","Item"),txt("نوع فایل","File Type"),txt("نام فایل","File Name"),txt("اندازه (KB)","Size (KB)"),txt("پیش‌نمایش تصویر / شرح","Image Preview / Note")]);styleHeader(evidenceHead);evidence.columns=[{width:15},{width:35},{width:16},{width:38},{width:16},{width:44}];
  const binary=wb.addWorksheet(txt("داده رسانه‌ای","Media Data"));setSheet(binary);binary.state="veryHidden";const binaryHead=binary.addRow([txt("کد آیتم","Item Code"),txt("نام فایل","File Name"),txt("نوع فایل","File Type"),txt("شماره بخش","Part No."),txt("دادهٔ رمزگذاری‌شده","Encoded Data")]);styleHeader(binaryHead);binary.columns=[{width:15},{width:36},{width:22},{width:12},{width:110}];
  let evidenceRow=2;Object.entries(state.attachments||{}).forEach(([key,files])=>files.forEach(file=>{const item=key.split("/").pop();const supportedImage=/^image\/(png|jpeg|gif)$/i.test(file.type);evidence.addRow([key,item,file.type,file.name,Math.round((file.size||0)/1024),supportedImage?txt("تصویر در این ردیف درج شده است","Image embedded in this row"):txt("فایل در شیت پنهان داده رسانه‌ای ذخیره شده است","The file is stored in the hidden Media Data sheet")]);if(supportedImage){try{const ext=file.type.split("/")[1].toLowerCase();const imageId=wb.addImage({base64:String(file.data||"").split(",")[1]||file.data,extension:ext});evidence.addImage(imageId,{tl:{col:5,row:evidenceRow-1},ext:{width:210,height:130}});evidence.getRow(evidenceRow).height=104}catch(_){evidence.getCell(evidenceRow,6).value=txt("ثبت تصویر ناموفق بود؛ داده فایل در شیت پنهان ذخیره شده است","Image embedding failed; file data is retained in the hidden sheet")}}const base64=String(file.data||"").split(",")[1]||"";for(let i=0,part=1;i<base64.length;i+=30000,part++)binary.addRow([key,file.name,file.type,part,base64.slice(i,i+30000)]);evidenceRow++}));
  addVehicleViewsWorksheet(wb,state.vehiclePhotos||{},fa);
  const buffer=await wb.xlsx.writeBuffer();const blob=new Blob([buffer],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`vehicle_assessment_${englishFileToken(state.metadata.model,"vehicle")}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}
function setLocale(next){locale=next;document.documentElement.lang=locale;document.documentElement.dir=locale==="fa"?"rtl":"ltr";document.body.classList.toggle("english",locale==="en");const languageLabel=locale==="fa"?"زبان انگلیسی":"Persian Language";const languageButton=$("#languageButton"),entryLanguageButton=$("#entryLanguageButton");if(languageButton){languageButton.textContent=languageLabel;languageButton.setAttribute("aria-label",languageLabel)}if(entryLanguageButton){entryLanguageButton.textContent=languageLabel;entryLanguageButton.setAttribute("aria-label",languageLabel)}document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=tr(el.dataset.i18n));document.querySelectorAll("[data-i18n-aria]").forEach(el=>el.setAttribute("aria-label",tr(el.dataset.i18nAria)));document.querySelectorAll("[data-i18n-alt]").forEach(el=>el.alt=tr(el.dataset.i18nAlt));$("#switchRoleButton").textContent=locale==="fa"?"تغییر نقش":"Switch Role";document.title=locale==="fa"?"سامانه ارزیابی خودرو":"Vehicle Assessment System";renderScoreGuide();renderMetadata();renderVehiclePhotos();renderTabs();renderCriteria();update();if(currentRole==="expert"&&window.renderExpertPanel)window.renderExpertPanel()}
function resetAssessment(){if(!confirm(tr("newConfirm")))return;localStorage.removeItem("bamco-vehicle-assessment");localStorage.removeItem("bamco-vehicle-expert-weights");localStorage.removeItem("bamco-manager-weight-control");sessionStorage.removeItem("bamco-second-vehicle-comparison");sessionStorage.removeItem("bamco-multi-vehicle-comparisons");sessionStorage.removeItem("bamco-comparison-vehicle-count");state={metadata:{date:isoLocal(new Date())},scores:{},notes:{},weights:{},attachments:{},vehiclePhotos:{},finalComments:{evaluator:"",expert:"",manager:""},workflow:{locked:false,everFinalized:false,finalizedAt:null,finalizedBy:"",editSession:null,editAuthorization:null},auditTrail:[]};window.location.reload()}
function applyRole(){const manager=currentRole==="manager",expert=currentRole==="expert";document.body.classList.toggle("managerMode",manager);document.body.classList.toggle("expertMode",expert);document.querySelectorAll(".managerOnly").forEach(el=>el.hidden=!manager);document.querySelectorAll(".evaluatorOnly").forEach(el=>el.hidden=manager||expert);$("#criteria").closest(".assessmentLayout").hidden=manager||expert;$(".metadata").hidden=manager||expert;$("#expertPanel").hidden=!expert;$("#expertHeaderActions").hidden=!expert;$("#switchRoleButton").textContent=locale==="fa"?"تغییر نقش":"Switch role";renderTabs();renderCriteria();if(expert&&window.renderExpertPanel)window.renderExpertPanel();if(manager&&window.bindManagerControls)window.bindManagerControls();update();if(window.BAMCO_REFRESH_EDIT_PERMISSION_UI)window.BAMCO_REFRESH_EDIT_PERMISSION_UI();}
function enter(role){currentRole=role;$("#entryScreen").hidden=true;$("#appShell").hidden=false;applyRole();window.scrollTo({top:0,behavior:"instant"})}
function init(){try{const saved=JSON.parse(localStorage.getItem("bamco-vehicle-assessment"));if(saved)state={...state,...saved,metadata:{...state.metadata,...saved.metadata},attachments:{...state.attachments,...(saved.attachments||{})},vehiclePhotos:{...state.vehiclePhotos,...(saved.vehiclePhotos||{})},finalComments:{...state.finalComments,...(saved.finalComments||{})}}}catch(_){}setLocale("fa");document.querySelectorAll("[data-role]").forEach(el=>el.addEventListener("click",()=>enter(el.dataset.role)));$("#switchRoleButton").addEventListener("click",()=>{$("#appShell").hidden=true;$("#entryScreen").hidden=false;window.scrollTo({top:0,behavior:"instant"})});$("#languageButton").addEventListener("click",()=>setLocale(locale==="fa"?"en":"fa"));$("#entryLanguageButton").addEventListener("click",()=>setLocale(locale==="fa"?"en":"fa"));$("#saveButton")?.addEventListener("click",download);$("#excelButton").addEventListener("click",exportExcel);$("#printButton").addEventListener("click",()=>window.print());$("#resetButton").addEventListener("click",resetAssessment);$("#loadInput").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result),loaded=data.state||data?.payload?.state||data?.payload||data;const restoredAudit=Array.isArray(data.auditTrail)?data.auditTrail:(Array.isArray(loaded.auditTrail)?loaded.auditTrail:state.auditTrail||[]),restoredWorkflow={...(state.workflow||{}),...(loaded.workflow||{}),...(data.workflow||{})};state={...state,...loaded,metadata:{...state.metadata,...(loaded.metadata||{})},attachments:{...state.attachments,...(loaded.attachments||{})},vehiclePhotos:{...state.vehiclePhotos,...(loaded.vehiclePhotos||{})},finalComments:{...state.finalComments,...(loaded.finalComments||{}),...(data.finalComments||{})},auditTrail:restoredAudit,workflow:restoredWorkflow};if(data.expertState&&window.restoreExpertBackup)window.restoreExpertBackup(data.expertState);if(data.managerWeightState&&window.restoreManagerWeightBackup)window.restoreManagerWeightBackup(data.managerWeightState);renderMetadata();renderVehiclePhotos();renderTabs();renderCriteria();update();persist();window.dispatchEvent(new CustomEvent("bamco:case-restored",{detail:{data,loaded}}))}catch(_){alert(tr("loadError"))}};reader.readAsText(f)})}
init();
