/* v62 — restore compact entry layout, official logo, ordered login fields, polished criterion tooltip */
(()=>{
  const q=(sel,root=document)=>root.querySelector(sel);
  const isFa=()=>document.documentElement.lang!=='en'&&!document.documentElement.classList.contains('english');
  function injectStyles(){
    let style=q('#bamco-v61-styles');if(!style){style=document.createElement('style');style.id='bamco-v61-styles';document.head.appendChild(style)}
    style.textContent=`
      #entryScreen .entryCard{max-width:920px!important;width:min(920px,calc(100vw - 32px))!important;padding:26px 38px 22px!important}
      #entryScreen .entryBrand{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:8px!important;min-height:0!important;padding:6px 12px 14px!important;text-align:center!important}
      #entryScreen .entryBrand img{content:url('./bamco-logo.svg?v=62')!important;display:block!important;width:min(430px,72vw)!important;max-width:430px!important;height:170px!important;margin:0 auto!important;object-fit:contain!important}
      #entryScreen .entryBrand>div{display:none!important}
      #entryScreen .entryTabs{max-width:620px!important;margin:0 auto 22px!important}
      #entryScreen .entryTabPanel{max-width:620px!important;margin-inline:auto!important}
      #entryScreen .entryIntro{text-align:center!important;margin-bottom:18px!important}
      #entryScreen .entryAuthForm{display:grid!important;grid-template-columns:1fr!important;gap:13px!important;max-width:520px!important;margin:0 auto!important;padding:20px!important;box-sizing:border-box!important}
      #entryScreen .entryAuthForm>label{display:grid!important;grid-template-columns:1fr!important;gap:7px!important;width:100%!important;text-align:right!important}
      #entryScreen .entryAuthForm input{width:100%!important;box-sizing:border-box!important;min-height:46px!important}
      #entryScreen .bamcoCaptcha{order:30!important;width:100%!important;box-sizing:border-box!important;margin:2px 0 0!important;padding:13px 14px!important;border:1px solid #cbdde8!important;border-radius:12px!important;background:#f7fafc!important;box-shadow:none!important}
      #entryScreen .bamcoCaptchaHead{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;margin-bottom:9px!important}
      #entryScreen .bamcoCaptchaHead strong{color:#173f63!important;font-size:13px!important;font-weight:800!important}
      #entryScreen .bamcoCaptchaRefresh{border:1px solid #bdd2e0!important;background:#fff!important;color:#174f76!important;border-radius:8px!important;width:38px!important;height:36px!important;cursor:pointer!important;font-weight:900!important}
      #entryScreen .bamcoCaptchaRow{display:grid!important;grid-template-columns:145px 1fr!important;gap:10px!important;align-items:center!important}
      #entryScreen .bamcoCaptchaQuestion{display:flex!important;align-items:center!important;justify-content:center!important;min-height:44px!important;border-radius:9px!important;background:#174a72!important;color:#fff!important;font:800 17px/1.2 Tahoma,Arial,sans-serif!important;direction:ltr!important}
      #entryScreen .bamcoCaptchaInput{min-height:44px!important;text-align:center!important}
      #entryScreen .bamcoCaptchaMessage{display:block!important;min-height:18px!important;margin-top:7px!important;color:#687f90!important;font-size:11px!important;font-weight:600!important}
      #entryScreen #authLoginButton{order:40!important;width:100%!important;min-height:46px!important;margin:0!important}
      #entryScreen #entryAuthMessage{order:50!important}
      #entryScreen #authLoginButton[data-captcha-locked="1"]{opacity:.58!important;cursor:not-allowed!important}
      #entryScreen .bamcoCaptcha.ok{border-color:#a8d1bf!important;background:#f6fbf8!important}#entryScreen .bamcoCaptcha.ok .bamcoCaptchaMessage{color:#187a54!important}
      #entryScreen .bamcoCaptcha.bad{border-color:#dfb1b6!important;background:#fff8f8!important}#entryScreen .bamcoCaptcha.bad .bamcoCaptchaMessage{color:#a83042!important}
      #managerComparisonCard .v52QuestionTitle{cursor:help!important;text-decoration-line:underline!important;text-decoration-style:dotted!important;text-underline-offset:4px!important;text-decoration-color:#8ba4b7!important}
      #bamcoCriterionTooltip{position:fixed!important;z-index:2147483000!important;display:none;width:min(390px,calc(100vw - 28px))!important;max-height:min(340px,58vh)!important;overflow:auto!important;padding:16px 18px!important;border:1px solid #c8dbe6!important;border-radius:14px!important;background:#f8fbfd!important;color:#35566d!important;box-shadow:0 14px 34px rgba(22,63,99,.18)!important;font-family:'B Nazanin','BNazanin','Nazanin',Tahoma,Arial,sans-serif!important;font-size:15px!important;font-weight:400!important;line-height:1.9!important;text-align:justify!important;text-align-last:right!important;direction:rtl!important;pointer-events:none!important}
      #bamcoCriterionTooltip b{display:block!important;margin-bottom:5px!important;color:#163f63!important;font-size:16px!important;font-weight:700!important;text-align:right!important}
      #bamcoCriterionTooltip .bamcoTipSub{display:block!important;margin-bottom:7px!important;color:#147b86!important;font-size:13px!important;font-weight:700!important;text-align:right!important}
      #bamcoCriterionTooltip .bamcoTipBody{display:block!important;text-align:justify!important}
      .english #bamcoCriterionTooltip{direction:ltr!important;text-align:left!important;text-align-last:left!important;font-family:'Times New Roman',serif!important;font-size:13px!important}
      @media(max-width:650px){#entryScreen .entryCard{padding:20px 16px!important}#entryScreen .entryBrand img{width:min(350px,84vw)!important;height:145px!important}#entryScreen .entryAuthForm{padding:14px!important}#entryScreen .bamcoCaptchaRow{grid-template-columns:1fr!important}}
    `;
  }
  function makeChallenge(){const a=2+Math.floor(Math.random()*8),b=1+Math.floor(Math.random()*8),add=Math.random()>.35;return add?{text:`${a} + ${b} = ?`,answer:a+b}:{text:`${a+b} − ${b} = ?`,answer:a}}
  let captcha={challenge:null,passed:false};
  function syncLoginLock(){const button=q('#authLoginButton');if(!button)return;button.dataset.captchaLocked=captcha.passed?'0':'1';button.setAttribute('aria-disabled',captcha.passed?'false':'true')}
  function refreshCaptcha(focus=false){captcha.challenge=makeChallenge();captcha.passed=false;const box=q('#bamcoEntryCaptcha'),question=q('#bamcoCaptchaQuestion'),input=q('#bamcoCaptchaInput'),msg=q('#bamcoCaptchaMessage');if(question)question.textContent=captcha.challenge.text;if(input){input.value='';if(focus)input.focus()}box?.classList.remove('ok','bad');if(msg)msg.textContent=isFa()?'پاسخ عبارت بالا را وارد کنید.':'Enter the answer above.';syncLoginLock()}
  function validateCaptcha(){const box=q('#bamcoEntryCaptcha'),input=q('#bamcoCaptchaInput'),msg=q('#bamcoCaptchaMessage');if(!input||!captcha.challenge)return false;const normalized=String(input.value||'').replace(/[۰-۹]/g,d=>'0123456789'['۰۱۲۳۴۵۶۷۸۹'.indexOf(d)]).trim(),ok=normalized!==''&&Number(normalized)===captcha.challenge.answer;captcha.passed=ok;box?.classList.toggle('ok',ok);box?.classList.toggle('bad',!ok&&normalized!=='');if(msg)msg.textContent=ok?(isFa()?'تأیید شد.':'Verified.'):(normalized?(isFa()?'پاسخ کپچا صحیح نیست.':'Incorrect captcha answer.'):(isFa()?'پاسخ عبارت بالا را وارد کنید.':'Enter the answer above.'));syncLoginLock();return ok}
  function installCaptcha(){const form=q('#entryAuthForm'),login=q('#authLoginButton');if(!form||!login)return;let box=q('#bamcoEntryCaptcha');if(!box){box=document.createElement('div');box.className='bamcoCaptcha';box.id='bamcoEntryCaptcha';box.innerHTML=`<div class="bamcoCaptchaHead"><strong>${isFa()?'تأیید انسانی':'Human verification'}</strong><button class="bamcoCaptchaRefresh" id="bamcoCaptchaRefresh" type="button" aria-label="${isFa()?'کپچای جدید':'New captcha'}">↻</button></div><div class="bamcoCaptchaRow"><div class="bamcoCaptchaQuestion" id="bamcoCaptchaQuestion"></div><input class="bamcoCaptchaInput" id="bamcoCaptchaInput" inputmode="numeric" autocomplete="off" placeholder="${isFa()?'پاسخ کپچا':'Captcha answer'}"></div><small class="bamcoCaptchaMessage" id="bamcoCaptchaMessage"></small>`;form.insertBefore(box,login);q('#bamcoCaptchaRefresh')?.addEventListener('click',()=>refreshCaptcha(true));q('#bamcoCaptchaInput')?.addEventListener('input',validateCaptcha);form.addEventListener('submit',event=>{if(validateCaptcha())return;event.preventDefault();event.stopImmediatePropagation();q('#bamcoCaptchaInput')?.focus()},true);refreshCaptcha()}}
  function setOfficialLogo(){const img=q('#entryScreen .entryBrand img');if(img){img.src='./bamco-logo.svg?v=62';img.removeAttribute('srcset');img.removeAttribute('hidden');img.style.visibility='visible';img.style.opacity='1'}}
  const normalize=v=>String(v||'').replace(/\s+/g,' ').trim();
  function findItemByVisibleTitle(text){const wanted=normalize(text);for(const main of(window.ASSESSMENT_CRITERIA||[]))for(const sub of(main.subgroups||[]))for(const item of(sub.items||[])){const candidates=[item.titleFa,item.titleEn,item.textFa,item.textEn].map(normalize).filter(Boolean);if(candidates.includes(wanted))return{main,sub,item}}return null}
  function ensureTooltip(){let tip=q('#bamcoCriterionTooltip');if(!tip){tip=document.createElement('div');tip.id='bamcoCriterionTooltip';tip.setAttribute('role','tooltip');document.body.appendChild(tip)}return tip}
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  function tooltipContent(label){const hit=findItemByVisibleTitle(label.textContent);if(!hit)return null;const{sub,item}=hit,fa=isFa();return{heading:fa?(item.titleFa||'توضیح شاخص'):(item.titleEn||item.titleFa||'Criterion'),description:fa?(item.textFa||item.exampleFa||''):(item.textEn||item.textFa||item.exampleEn||item.exampleFa||''),subgroup:fa?(sub.titleFa||''):(sub.titleEn||sub.titleFa||'')}}
  function showTooltip(label,event){const d=tooltipContent(label);if(!d)return;const tip=ensureTooltip();tip.innerHTML=`<b>${esc(d.heading)}</b>${d.subgroup?`<span class="bamcoTipSub">${esc(d.subgroup)}</span>`:''}<span class="bamcoTipBody">${esc(d.description)}</span>`;tip.style.display='block';moveTooltip(event)}
  function moveTooltip(event){const tip=q('#bamcoCriterionTooltip');if(!tip||tip.style.display==='none')return;const gap=14,r=tip.getBoundingClientRect();let left=event.clientX+gap,top=event.clientY+gap;if(left+r.width>innerWidth-8)left=event.clientX-r.width-gap;if(top+r.height>innerHeight-8)top=event.clientY-r.height-gap;tip.style.left=Math.max(8,left)+'px';tip.style.top=Math.max(8,top)+'px'}
  function hideTooltip(){const tip=q('#bamcoCriterionTooltip');if(tip)tip.style.display='none'}
  document.addEventListener('mouseover',e=>{const l=e.target?.closest?.('#managerComparisonCard .v52QuestionTitle');if(l)showTooltip(l,e)},true);document.addEventListener('mousemove',e=>{if(e.target?.closest?.('#managerComparisonCard .v52QuestionTitle'))moveTooltip(e)},true);document.addEventListener('mouseout',e=>{const l=e.target?.closest?.('#managerComparisonCard .v52QuestionTitle');if(l&&!l.contains(e.relatedTarget))hideTooltip()},true);addEventListener('scroll',hideTooltip,true);
  function boot(){injectStyles();setOfficialLogo();installCaptcha()}
  const observer=new MutationObserver(()=>{setOfficialLogo();installCaptcha()});observer.observe(document.documentElement,{subtree:true,childList:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();