/* v65 — single-pass entry UI: supplied BAMCO Persian logo + compact captcha + comparison tooltip */
(()=>{
  const q=(s,r=document)=>r.querySelector(s);
  const isFa=()=>document.documentElement.lang!=='en'&&!document.documentElement.classList.contains('english');
  function styles(){
    let el=q('#bamco-v65-styles');if(!el){el=document.createElement('style');el.id='bamco-v65-styles';document.head.appendChild(el)}
    el.textContent=`
      #entryScreen .entryCard{max-width:920px!important;width:min(920px,calc(100vw - 32px))!important;padding:26px 38px 22px!important}
      #entryScreen .entryBrand{display:flex!important;align-items:center!important;justify-content:center!important;min-height:0!important;padding:2px 12px 10px!important;text-align:center!important}
      #entryScreen .entryBrand img{content:url('./bamco-logo.webp?v=65')!important;display:block!important;width:min(405px,70vw)!important;max-width:405px!important;height:155px!important;margin:0 auto!important;object-fit:contain!important;border-radius:0!important}
      #entryScreen .entryBrand>div{display:none!important}
      #entryScreen .entryTabs{max-width:620px!important;margin:0 auto 18px!important}
      #entryScreen .entryTabPanel{max-width:620px!important;margin-inline:auto!important}
      #entryScreen .entryIntro{text-align:center!important;margin-bottom:16px!important}
      #entryScreen .entryAuthForm{display:grid!important;grid-template-columns:1fr!important;gap:12px!important;max-width:520px!important;margin:0 auto!important;padding:18px!important;box-sizing:border-box!important}
      #entryScreen .entryAuthForm>label{display:grid!important;grid-template-columns:1fr!important;gap:7px!important;width:100%!important;text-align:right!important}
      #entryScreen .entryAuthForm input{width:100%!important;box-sizing:border-box!important;min-height:46px!important}
      #entryScreen .bamcoCaptcha{order:30!important;width:100%!important;box-sizing:border-box!important;margin:0!important;padding:9px 10px!important;border:1px solid #cbdde8!important;border-radius:11px!important;background:#f7fafc!important;box-shadow:none!important}
      #entryScreen .bamcoCaptchaHead{display:none!important}
      #entryScreen .bamcoCaptchaRow{display:grid!important;grid-template-columns:38px 112px minmax(150px,1fr)!important;gap:8px!important;align-items:center!important;direction:ltr!important}
      #entryScreen .bamcoCaptchaRefresh{display:flex!important;align-items:center!important;justify-content:center!important;width:38px!important;height:38px!important;border:1px solid #bdd2e0!important;background:#fff!important;color:#174f76!important;border-radius:8px!important;cursor:pointer!important;font-weight:900!important;grid-column:1!important}
      #entryScreen .bamcoCaptchaQuestion{display:flex!important;align-items:center!important;justify-content:center!important;min-height:38px!important;border-radius:8px!important;background:#174a72!important;color:#fff!important;font:800 14px/1.2 Tahoma,Arial,sans-serif!important;direction:ltr!important;grid-column:2!important}
      #entryScreen .bamcoCaptchaInput{min-height:38px!important;text-align:center!important;grid-column:3!important}
      #entryScreen .bamcoCaptchaMessage{display:block!important;min-height:14px!important;margin-top:4px!important;color:#687f90!important;font-size:10px!important;font-weight:600!important;direction:rtl!important;text-align:right!important}
      #entryScreen #authLoginButton{order:40!important;width:100%!important;min-height:46px!important;margin:0!important}
      #entryScreen #entryAuthMessage{order:50!important}
      #entryScreen #authLoginButton[data-captcha-locked="1"]{opacity:.58!important;cursor:not-allowed!important}
      #entryScreen .bamcoCaptcha.ok{border-color:#a8d1bf!important;background:#f6fbf8!important}#entryScreen .bamcoCaptcha.ok .bamcoCaptchaMessage{color:#187a54!important}
      #entryScreen .bamcoCaptcha.bad{border-color:#dfb1b6!important;background:#fff8f8!important}#entryScreen .bamcoCaptcha.bad .bamcoCaptchaMessage{color:#a83042!important}
      #managerComparisonCard .v52QuestionTitle{cursor:help!important;text-decoration-line:underline!important;text-decoration-style:dotted!important;text-underline-offset:4px!important;text-decoration-color:#8ba4b7!important}
      #bamcoCriterionTooltip{position:fixed!important;z-index:2147483000!important;display:none;width:min(390px,calc(100vw - 28px))!important;max-height:min(340px,58vh)!important;overflow:auto!important;padding:16px 18px!important;border:1px solid #c8dbe6!important;border-radius:14px!important;background:#f8fbfd!important;color:#35566d!important;box-shadow:0 14px 34px rgba(22,63,99,.18)!important;font-family:'B Nazanin','BNazanin','Nazanin',Tahoma,Arial,sans-serif!important;font-size:15px!important;font-weight:400!important;line-height:1.9!important;text-align:justify!important;text-align-last:right!important;direction:rtl!important;pointer-events:none!important}
      #bamcoCriterionTooltip b{display:block!important;margin-bottom:5px!important;color:#163f63!important;font-size:16px!important;font-weight:700!important;text-align:right!important}
      #bamcoCriterionTooltip .bamcoTipSub{display:block!important;margin-bottom:7px!important;color:#147b86!important;font-size:13px!important;font-weight:700!important;text-align:right!important}
      #bamcoCriterionTooltip .bamcoTipBody{display:block!important;text-align:justify!important}
      .english #bamcoCriterionTooltip{direction:ltr!important;text-align:left!important;text-align-last:left!important;font-family:'Times New Roman',serif!important;font-size:13px!important}
      @media(max-width:650px){#entryScreen .entryCard{padding:20px 16px!important}#entryScreen .entryBrand img{width:min(340px,84vw)!important;height:135px!important}#entryScreen .entryAuthForm{padding:14px!important}#entryScreen .bamcoCaptchaRow{grid-template-columns:36px 102px minmax(100px,1fr)!important}}
    `;
  }
  function logo(){const img=q('#entryScreen .entryBrand img');if(img){img.src='./bamco-logo.webp?v=65';img.removeAttribute('srcset');img.style.content="url('./bamco-logo.webp?v=65')";img.style.visibility='visible';img.style.opacity='1'}}
  const make=()=>{const a=2+Math.floor(Math.random()*8),b=1+Math.floor(Math.random()*8),add=Math.random()>.35;return add?{text:`${a} + ${b} = ?`,answer:a+b}:{text:`${a+b} − ${b} = ?`,answer:a}};
  let challenge=null,passed=false;
  function lock(){const b=q('#authLoginButton');if(b){b.dataset.captchaLocked=passed?'0':'1';b.setAttribute('aria-disabled',passed?'false':'true')}}
  function refresh(focus=false){challenge=make();passed=false;const box=q('#bamcoEntryCaptcha'),qq=q('#bamcoCaptchaQuestion'),inp=q('#bamcoCaptchaInput'),msg=q('#bamcoCaptchaMessage');if(qq)qq.textContent=challenge.text;if(inp){inp.value='';if(focus)inp.focus()}box?.classList.remove('ok','bad');if(msg)msg.textContent=isFa()?'پاسخ عبارت بالا را وارد کنید.':'Enter the answer above.';lock()}
  function validate(){const box=q('#bamcoEntryCaptcha'),inp=q('#bamcoCaptchaInput'),msg=q('#bamcoCaptchaMessage');if(!inp||!challenge)return false;const val=String(inp.value||'').replace(/[۰-۹]/g,d=>'0123456789'['۰۱۲۳۴۵۶۷۸۹'.indexOf(d)]).trim();passed=val!==''&&Number(val)===challenge.answer;box?.classList.toggle('ok',passed);box?.classList.toggle('bad',!passed&&val!=='');if(msg)msg.textContent=passed?(isFa()?'تأیید شد.':'Verified.'):(val?(isFa()?'پاسخ کپچا صحیح نیست.':'Incorrect captcha answer.'):(isFa()?'پاسخ عبارت بالا را وارد کنید.':'Enter the answer above.'));lock();return passed}
  function captcha(){const form=q('#entryAuthForm'),login=q('#authLoginButton');if(!form||!login||q('#bamcoEntryCaptcha'))return;const box=document.createElement('div');box.className='bamcoCaptcha';box.id='bamcoEntryCaptcha';box.innerHTML=`<div class="bamcoCaptchaHead"><strong>${isFa()?'تأیید انسانی':'Human verification'}</strong></div><div class="bamcoCaptchaRow"><button class="bamcoCaptchaRefresh" id="bamcoCaptchaRefresh" type="button" aria-label="${isFa()?'کپچای جدید':'New captcha'}">↻</button><div class="bamcoCaptchaQuestion" id="bamcoCaptchaQuestion"></div><input class="bamcoCaptchaInput" id="bamcoCaptchaInput" inputmode="numeric" autocomplete="off" placeholder="${isFa()?'پاسخ کپچا':'Captcha answer'}"></div><small class="bamcoCaptchaMessage" id="bamcoCaptchaMessage"></small>`;form.insertBefore(box,login);q('#bamcoCaptchaRefresh')?.addEventListener('click',()=>refresh(true));q('#bamcoCaptchaInput')?.addEventListener('input',validate);form.addEventListener('submit',e=>{if(validate())return;e.preventDefault();e.stopImmediatePropagation();q('#bamcoCaptchaInput')?.focus()},true);refresh()}
  const norm=v=>String(v||'').replace(/\s+/g,' ').trim(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function hit(text){const w=norm(text);for(const main of(window.ASSESSMENT_CRITERIA||[]))for(const sub of(main.subgroups||[]))for(const item of(sub.items||[])){if([item.titleFa,item.titleEn,item.textFa,item.textEn].map(norm).filter(Boolean).includes(w))return{sub,item}}return null}
  function tip(){let t=q('#bamcoCriterionTooltip');if(!t){t=document.createElement('div');t.id='bamcoCriterionTooltip';t.setAttribute('role','tooltip');document.body.appendChild(t)}return t}
  function show(label,e){const h=hit(label.textContent);if(!h)return;const fa=isFa(),t=tip(),heading=fa?(h.item.titleFa||'توضیح شاخص'):(h.item.titleEn||h.item.titleFa||'Criterion'),desc=fa?(h.item.textFa||h.item.exampleFa||''):(h.item.textEn||h.item.textFa||h.item.exampleEn||h.item.exampleFa||''),sub=fa?(h.sub.titleFa||''):(h.sub.titleEn||h.sub.titleFa||'');t.innerHTML=`<b>${esc(heading)}</b>${sub?`<span class="bamcoTipSub">${esc(sub)}</span>`:''}<span class="bamcoTipBody">${esc(desc)}</span>`;t.style.display='block';move(e)}
  function move(e){const t=q('#bamcoCriterionTooltip');if(!t||t.style.display==='none')return;const g=14,r=t.getBoundingClientRect();let l=e.clientX+g,top=e.clientY+g;if(l+r.width>innerWidth-8)l=e.clientX-r.width-g;if(top+r.height>innerHeight-8)top=e.clientY-r.height-g;t.style.left=Math.max(8,l)+'px';t.style.top=Math.max(8,top)+'px'}
  function hide(){const t=q('#bamcoCriterionTooltip');if(t)t.style.display='none'}
  document.addEventListener('mouseover',e=>{const l=e.target?.closest?.('#managerComparisonCard .v52QuestionTitle');if(l)show(l,e)},true);document.addEventListener('mousemove',e=>{if(e.target?.closest?.('#managerComparisonCard .v52QuestionTitle'))move(e)},true);document.addEventListener('mouseout',e=>{const l=e.target?.closest?.('#managerComparisonCard .v52QuestionTitle');if(l&&!l.contains(e.relatedTarget))hide()},true);addEventListener('scroll',hide,true);
  function apply(){styles();logo();captcha()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();